/*
Script generated by Aqua Data Studio 9.0.13 on Aug-14-2012 05:28:17 PM
Database: escolar-db
Schema: <All Schemas>
Objects: SEQUENCE, TABLE, INDEX
*/
ALTER TABLE "public"."unidad_educativa"
	DROP CONSTRAINT "fk_unidad_e_r_reg_uni_region" CASCADE 
GO
ALTER TABLE "public"."seccion"
	DROP CONSTRAINT "fk_seccion_relations_padre" CASCADE 
GO
ALTER TABLE "public"."seccion"
	DROP CONSTRAINT "fk_seccion_relations_base" CASCADE 
GO
ALTER TABLE "public"."seccion"
	DROP CONSTRAINT "fk_seccion_r_uni_edu_unidad_e" CASCADE 
GO
ALTER TABLE "public"."rol_persona"
	DROP CONSTRAINT "fk_rol_pers_r_rol_tr__rol" CASCADE 
GO
ALTER TABLE "public"."rol_persona"
	DROP CONSTRAINT "fk_rol_pers_r_pers_tr_persona" CASCADE 
GO
ALTER TABLE "public"."rol_opcion"
	DROP CONSTRAINT "fk_rol_opci_relations_rol" CASCADE 
GO
ALTER TABLE "public"."rol_opcion"
	DROP CONSTRAINT "fk_rol_opci_relations_opcion" CASCADE 
GO
ALTER TABLE "public"."rol"
	DROP CONSTRAINT "fk_rol_r_uni_edu" CASCADE 
GO
ALTER TABLE "public"."respuesta"
	DROP CONSTRAINT "fk_respuest_r_pre_res_pregunta" CASCADE 
GO
ALTER TABLE "public"."respuesta"
	DROP CONSTRAINT "fk_respuest_r_not_res_nota" CASCADE 
GO
ALTER TABLE "public"."registro"
	DROP CONSTRAINT "fk_registro_r_tr_mes__mes_clas" CASCADE 
GO
ALTER TABLE "public"."region"
	DROP CONSTRAINT "fk_region_r_pai_reg_pais" CASCADE 
GO
ALTER TABLE "public"."recurso_materia"
	DROP CONSTRAINT "fk_recurso__r_rec_tr__recurso" CASCADE 
GO
ALTER TABLE "public"."recurso_materia"
	DROP CONSTRAINT "fk_recurso__r_mat_tr__materia" CASCADE 
GO
ALTER TABLE "public"."recurso_keyword"
	DROP CONSTRAINT "fk_recurso__r_rec_tr__recurso" CASCADE 
GO
ALTER TABLE "public"."recurso_keyword"
	DROP CONSTRAINT "fk_recurso__r_key_tr__detalle_" CASCADE 
GO
ALTER TABLE "public"."recurso_herramienta_evaluacion"
	DROP CONSTRAINT "fk_recurso__r_rec_tr__recurso" CASCADE 
GO
ALTER TABLE "public"."recurso_herramienta_evaluacion"
	DROP CONSTRAINT "fk_recurso__r_her_eva_herramie" CASCADE 
GO
ALTER TABLE "public"."recurso_herramienta_clase"
	DROP CONSTRAINT "fk_recurso__r_rec_tr__recurso" CASCADE 
GO
ALTER TABLE "public"."recurso_herramienta_clase"
	DROP CONSTRAINT "fk_recurso__r_her_cla_herramie" CASCADE 
GO
ALTER TABLE "public"."recurso"
	DROP CONSTRAINT "fk_recurso_r_her_eva_herramie" CASCADE 
GO
ALTER TABLE "public"."recurso"
	DROP CONSTRAINT "fk_recurso_r_det_cat_detalle_" CASCADE 
GO
ALTER TABLE "public"."pregunta"
	DROP CONSTRAINT "fk_pregunta_r_her_eva_herramie" CASCADE 
GO
ALTER TABLE "public"."persona_grupo"
	DROP CONSTRAINT "fk_persona__r_per_tr__persona" CASCADE 
GO
ALTER TABLE "public"."persona_grupo"
	DROP CONSTRAINT "fk_persona__r_gru_tr__grupo" CASCADE 
GO
ALTER TABLE "public"."persona"
	DROP CONSTRAINT "fk_persona_r_det_cat_detalle_" CASCADE 
GO
ALTER TABLE "public"."periodo"
	DROP CONSTRAINT "fk_periodo_r_reg_per_region" CASCADE 
GO
ALTER TABLE "public"."paralelo"
	DROP CONSTRAINT "fk_paralelo_r_cur_par_curso" CASCADE 
GO
ALTER TABLE "public"."opcion_respuesta"
	DROP CONSTRAINT "fk_opcion_r_r_res_opc_respuest" CASCADE 
GO
ALTER TABLE "public"."opcion_respuesta"
	DROP CONSTRAINT "fk_opcion_r_r_opc_pre_opcion_p" CASCADE 
GO
ALTER TABLE "public"."opcion_pregunta"
	DROP CONSTRAINT "fk_opcion_p_r_pre_opc_pregunta" CASCADE 
GO
ALTER TABLE "public"."opcion"
	DROP CONSTRAINT "fk_opcion_relations_opcion" CASCADE 
GO
ALTER TABLE "public"."nota"
	DROP CONSTRAINT "fk_nota_r_mat_not_matricul" CASCADE 
GO
ALTER TABLE "public"."nota"
	DROP CONSTRAINT "fk_nota_r_her_cla_herramie" CASCADE 
GO
ALTER TABLE "public"."mes_setup"
	DROP CONSTRAINT "fk_mes_setu_r_sec_mes_seccion" CASCADE 
GO
ALTER TABLE "public"."mes_clase"
	DROP CONSTRAINT "fk_mes_clas_r_mes_set_mes_setu" CASCADE 
GO
ALTER TABLE "public"."mes_clase"
	DROP CONSTRAINT "fk_mes_clas_r_cla_tr__clase" CASCADE 
GO
ALTER TABLE "public"."matricula"
	DROP CONSTRAINT "fk_matricul_r_pers_ma_persona" CASCADE 
GO
ALTER TABLE "public"."matricula"
	DROP CONSTRAINT "fk_matricul_r_per_mat_periodo" CASCADE 
GO
ALTER TABLE "public"."matricula"
	DROP CONSTRAINT "fk_matricul_r_par_mat_paralelo" CASCADE 
GO
ALTER TABLE "public"."materia"
	DROP CONSTRAINT "fk_materia_r_uni_edu_unidad_e" CASCADE 
GO
ALTER TABLE "public"."materia"
	DROP CONSTRAINT "fk_materia_r_tip_mat_tipo_mat" CASCADE 
GO
ALTER TABLE "public"."materia"
	DROP CONSTRAINT "fk_materia_r_mat_base" CASCADE 
GO
ALTER TABLE "public"."historico_materia"
	DROP CONSTRAINT "fk_historic_r_pers_hi_persona" CASCADE 
GO
ALTER TABLE "public"."historico_materia"
	DROP CONSTRAINT "fk_historic_r_per_his_periodo" CASCADE 
GO
ALTER TABLE "public"."historico_materia"
	DROP CONSTRAINT "fk_historic_r_mat_his_materia" CASCADE 
GO
ALTER TABLE "public"."historico_materia"
	DROP CONSTRAINT "fk_historic_r_cur_his_curso" CASCADE 
GO
ALTER TABLE "public"."historico_academico_mensual"
	DROP CONSTRAINT "fk_historic_r_profe_h_persona" CASCADE 
GO
ALTER TABLE "public"."historico_academico_mensual"
	DROP CONSTRAINT "fk_historic_r_pers_hi_persona" CASCADE 
GO
ALTER TABLE "public"."historico_academico_mensual"
	DROP CONSTRAINT "fk_historic_r_per_his_periodo" CASCADE 
GO
ALTER TABLE "public"."historico_academico_mensual"
	DROP CONSTRAINT "fk_historic_r_mes_set_mes_setu" CASCADE 
GO
ALTER TABLE "public"."historico_academico_mensual"
	DROP CONSTRAINT "fk_historic_r_mat_his_materia" CASCADE 
GO
ALTER TABLE "public"."historico_academico_anual"
	DROP CONSTRAINT "fk_historic_r_profe_h_persona" CASCADE 
GO
ALTER TABLE "public"."historico_academico_anual"
	DROP CONSTRAINT "fk_historic_r_pers_hi_persona" CASCADE 
GO
ALTER TABLE "public"."historico_academico_anual"
	DROP CONSTRAINT "fk_historic_r_per_his_periodo" CASCADE 
GO
ALTER TABLE "public"."historico_academico_anual"
	DROP CONSTRAINT "fk_historic_r_mat_his_materia" CASCADE 
GO
ALTER TABLE "public"."herramienta_clase_agrupacion"
	DROP CONSTRAINT "fk_herramie_r_sec_her_seccion" CASCADE 
GO
ALTER TABLE "public"."herramienta_clase"
	DROP CONSTRAINT "fk_herramie_r_tr_mes__mes_clas" CASCADE 
GO
ALTER TABLE "public"."herramienta_clase"
	DROP CONSTRAINT "fk_herramie_r_her_eva_herramie" CASCADE 
GO
ALTER TABLE "public"."herramienta_clase"
	DROP CONSTRAINT "fk_herramie_r_her_cla_herramie" CASCADE 
GO
ALTER TABLE "public"."grupo"
	DROP CONSTRAINT "fk_grupo_r_pers_gr_persona" CASCADE 
GO
ALTER TABLE "public"."grupo"
	DROP CONSTRAINT "fk_grupo_r_her_cla_herramie" CASCADE 
GO
ALTER TABLE "public"."estudiante_representante"
	DROP CONSTRAINT "fk_estudian_r_per_tr__persona" CASCADE 
GO
ALTER TABLE "public"."estudiante_representante"
	DROP CONSTRAINT "fk_estudian_r_per_tr__per" CASCADE 
GO
ALTER TABLE "public"."estudiante_representante"
	DROP CONSTRAINT "fk_estudian_r_det_cat_detalle_" CASCADE 
GO
ALTER TABLE "public"."dia_festivo"
	DROP CONSTRAINT "fk_dia_fest_r_per_dia_periodo" CASCADE 
GO
ALTER TABLE "public"."detalle_catalogo"
	DROP CONSTRAINT "fk_detalle__r_cat_tip_catalogo" CASCADE 
GO
ALTER TABLE "public"."datos_representante"
	DROP CONSTRAINT "fk_datos_re_r_pers_da_persona" CASCADE 
GO
ALTER TABLE "public"."datos_estudiante"
	DROP CONSTRAINT "fk_datos_es_r_pers_da_persona" CASCADE 
GO
ALTER TABLE "public"."datos_empleado_ue"
	DROP CONSTRAINT "fk_datos_em_r_uni_edu_unidad_e" CASCADE 
GO
ALTER TABLE "public"."datos_empleado_ue"
	DROP CONSTRAINT "fk_datos_em_r_per_dat_persona" CASCADE 
GO
ALTER TABLE "public"."curso_materia"
	DROP CONSTRAINT "fk_curso_ma_r_mat_tr__materia" CASCADE 
GO
ALTER TABLE "public"."curso_materia"
	DROP CONSTRAINT "fk_curso_ma_r_cur_tr__curso" CASCADE 
GO
ALTER TABLE "public"."curso"
	DROP CONSTRAINT "fk_curso_r_sec_cur_seccion" CASCADE 
GO
ALTER TABLE "public"."curso"
	DROP CONSTRAINT "fk_curso_r_cur_base" CASCADE 
GO
ALTER TABLE "public"."curso"
	DROP CONSTRAINT "fk_curso_r_cur_ante" CASCADE 
GO
ALTER TABLE "public"."continuidad_seccion"
	DROP CONSTRAINT "fk_continui_r_sec_sig_seccion" CASCADE 
GO
ALTER TABLE "public"."continuidad_seccion"
	DROP CONSTRAINT "fk_continui_r_sec_ant_seccion" CASCADE 
GO
ALTER TABLE "public"."continuidad_materia"
	DROP CONSTRAINT "fk_continui_r_sec_sig" CASCADE 
GO
ALTER TABLE "public"."continuidad_materia"
	DROP CONSTRAINT "fk_continui_r_sec_ante" CASCADE 
GO
ALTER TABLE "public"."contenido"
	DROP CONSTRAINT "fk_contenid_r_mes_set_mes_setu" CASCADE 
GO
ALTER TABLE "public"."contenido"
	DROP CONSTRAINT "fk_contenid_r_mat_con_materia" CASCADE 
GO
ALTER TABLE "public"."configuracion_sistema"
	DROP CONSTRAINT "fk_configur_r_pers_co_persona" CASCADE 
GO
ALTER TABLE "public"."clase"
	DROP CONSTRAINT "fk_clase_r_pers_cl_persona" CASCADE 
GO
ALTER TABLE "public"."clase"
	DROP CONSTRAINT "fk_clase_r_per_cla_periodo" CASCADE 
GO
ALTER TABLE "public"."clase"
	DROP CONSTRAINT "fk_clase_r_par_cla_paralelo" CASCADE 
GO
ALTER TABLE "public"."clase"
	DROP CONSTRAINT "fk_clase_r_mat_cla_materia" CASCADE 
GO
ALTER TABLE "public"."catalogo_tipo"
	DROP CONSTRAINT "fk_catalogo_r_cat_tip_catalogo" CASCADE 
GO
DROP INDEX "public"."unidad_educativa_pkey"
GO
DROP INDEX "public"."tipo_materia_pkey"
GO
DROP INDEX "public"."seccion_pkey"
GO
DROP INDEX "public"."rol_pkey"
GO
DROP INDEX "public"."rol_persona_pkey"
GO
DROP INDEX "public"."rol_opcion_pkey"
GO
DROP INDEX "public"."respuesta_pkey"
GO
DROP INDEX "public"."registro_pkey"
GO
DROP INDEX "public"."region_pkey"
GO
DROP INDEX "public"."recurso_pkey"
GO
DROP INDEX "public"."recurso_materia_pkey"
GO
DROP INDEX "public"."recurso_keyword_pkey"
GO
DROP INDEX "public"."recurso_herramienta_evaluacion_pkey"
GO
DROP INDEX "public"."recurso_herramienta_clase_pkey"
GO
DROP INDEX "public"."pregunta_pkey"
GO
DROP INDEX "public"."persona_pkey"
GO
DROP INDEX "public"."persona_grupo_pkey"
GO
DROP INDEX "public"."periodo_pkey"
GO
DROP INDEX "public"."paralelo_pkey"
GO
DROP INDEX "public"."pais_pkey"
GO
DROP INDEX "public"."opcion_respuesta_pkey"
GO
DROP INDEX "public"."opcion_pregunta_pkey"
GO
DROP INDEX "public"."opcion_pkey"
GO
DROP INDEX "public"."nota_pkey"
GO
DROP INDEX "public"."mes_setup_pkey"
GO
DROP INDEX "public"."mes_clase_pkey"
GO
DROP INDEX "public"."matricula_pkey"
GO
DROP INDEX "public"."materia_pkey"
GO
DROP INDEX "public"."historico_materia_pkey"
GO
DROP INDEX "public"."historico_academico_mensual_pkey"
GO
DROP INDEX "public"."historico_academico_anual_pkey"
GO
DROP INDEX "public"."herramienta_evaluacion_pkey"
GO
DROP INDEX "public"."herramienta_clase_pkey"
GO
DROP INDEX "public"."herramienta_clase_agrupacion_pkey"
GO
DROP INDEX "public"."grupo_pkey"
GO
DROP INDEX "public"."estudiante_representante_pkey"
GO
DROP INDEX "public"."dia_festivo_pkey"
GO
DROP INDEX "public"."detalle_catalogo_pkey"
GO
DROP INDEX "public"."datos_representante_pkey"
GO
DROP INDEX "public"."datos_estudiante_pkey"
GO
DROP INDEX "public"."datos_empleado_ue_pkey"
GO
DROP INDEX "public"."curso_pkey"
GO
DROP INDEX "public"."curso_materia_pkey"
GO
DROP INDEX "public"."continuidad_seccion_pkey"
GO
DROP INDEX "public"."continuidad_materia_pkey"
GO
DROP INDEX "public"."contenido_pkey"
GO
DROP INDEX "public"."configuracion_sistema_pkey"
GO
DROP INDEX "public"."clase_pkey"
GO
DROP INDEX "public"."catalogo_tipo_pkey"
GO
DROP INDEX "pg_toast"."pg_toast_2619_index"
GO
DROP INDEX "pg_toast"."pg_toast_2618_index"
GO
DROP INDEX "pg_toast"."pg_toast_2609_index"
GO
DROP INDEX "pg_toast"."pg_toast_2606_index"
GO
DROP INDEX "pg_toast"."pg_toast_2604_index"
GO
DROP INDEX "pg_toast"."pg_toast_2396_index"
GO
DROP INDEX "pg_toast"."pg_toast_131448_index"
GO
DROP INDEX "pg_toast"."pg_toast_131435_index"
GO
DROP INDEX "pg_toast"."pg_toast_131412_index"
GO
DROP INDEX "pg_toast"."pg_toast_131404_index"
GO
DROP INDEX "pg_toast"."pg_toast_131396_index"
GO
DROP INDEX "pg_toast"."pg_toast_131368_index"
GO
DROP INDEX "pg_toast"."pg_toast_131360_index"
GO
DROP INDEX "pg_toast"."pg_toast_131347_index"
GO
DROP INDEX "pg_toast"."pg_toast_131339_index"
GO
DROP INDEX "pg_toast"."pg_toast_131331_index"
GO
DROP INDEX "pg_toast"."pg_toast_131323_index"
GO
DROP INDEX "pg_toast"."pg_toast_131315_index"
GO
DROP INDEX "pg_toast"."pg_toast_131307_index"
GO
DROP INDEX "pg_toast"."pg_toast_131299_index"
GO
DROP INDEX "pg_toast"."pg_toast_131291_index"
GO
DROP INDEX "pg_toast"."pg_toast_131268_index"
GO
DROP INDEX "pg_toast"."pg_toast_131255_index"
GO
DROP INDEX "pg_toast"."pg_toast_131247_index"
GO
DROP INDEX "pg_toast"."pg_toast_131239_index"
GO
DROP INDEX "pg_toast"."pg_toast_131231_index"
GO
DROP INDEX "pg_toast"."pg_toast_131223_index"
GO
DROP INDEX "pg_toast"."pg_toast_131190_index"
GO
DROP INDEX "pg_toast"."pg_toast_131182_index"
GO
DROP INDEX "pg_toast"."pg_toast_131154_index"
GO
DROP INDEX "pg_toast"."pg_toast_1262_index"
GO
DROP INDEX "pg_toast"."pg_toast_1260_index"
GO
DROP INDEX "pg_toast"."pg_toast_1255_index"
GO
DROP INDEX "pg_toast"."pg_toast_11459_index"
GO
DROP INDEX "pg_toast"."pg_toast_11454_index"
GO
DROP INDEX "pg_toast"."pg_toast_11449_index"
GO
DROP INDEX "pg_toast"."pg_toast_11444_index"
GO
DROP INDEX "pg_toast"."pg_toast_11439_index"
GO
DROP INDEX "pg_toast"."pg_toast_11434_index"
GO
DROP INDEX "pg_toast"."pg_toast_11429_index"
GO
DROP INDEX "pg_catalog"."pg_type_typname_nsp_index"
GO
DROP INDEX "pg_catalog"."pg_type_oid_index"
GO
DROP INDEX "pg_catalog"."pg_ts_template_tmplname_index"
GO
DROP INDEX "pg_catalog"."pg_ts_template_oid_index"
GO
DROP INDEX "pg_catalog"."pg_ts_parser_prsname_index"
GO
DROP INDEX "pg_catalog"."pg_ts_parser_oid_index"
GO
DROP INDEX "pg_catalog"."pg_ts_dict_oid_index"
GO
DROP INDEX "pg_catalog"."pg_ts_dict_dictname_index"
GO
DROP INDEX "pg_catalog"."pg_ts_config_oid_index"
GO
DROP INDEX "pg_catalog"."pg_ts_config_map_index"
GO
DROP INDEX "pg_catalog"."pg_ts_config_cfgname_index"
GO
DROP INDEX "pg_catalog"."pg_trigger_tgrelid_tgname_index"
GO
DROP INDEX "pg_catalog"."pg_trigger_tgconstrname_index"
GO
DROP INDEX "pg_catalog"."pg_trigger_oid_index"
GO
DROP INDEX "pg_catalog"."pg_tablespace_spcname_index"
GO
DROP INDEX "pg_catalog"."pg_tablespace_oid_index"
GO
DROP INDEX "pg_catalog"."pg_statistic_relid_att_index"
GO
DROP INDEX "pg_catalog"."pg_shdescription_o_c_index"
GO
DROP INDEX "pg_catalog"."pg_shdepend_reference_index"
GO
DROP INDEX "pg_catalog"."pg_shdepend_depender_index"
GO
DROP INDEX "pg_catalog"."pg_rewrite_rel_rulename_index"
GO
DROP INDEX "pg_catalog"."pg_rewrite_oid_index"
GO
DROP INDEX "pg_catalog"."pg_proc_proname_args_nsp_index"
GO
DROP INDEX "pg_catalog"."pg_proc_oid_index"
GO
DROP INDEX "pg_catalog"."pg_pltemplate_name_index"
GO
DROP INDEX "pg_catalog"."pg_opfamily_oid_index"
GO
DROP INDEX "pg_catalog"."pg_opfamily_am_name_nsp_index"
GO
DROP INDEX "pg_catalog"."pg_operator_oprname_l_r_n_index"
GO
DROP INDEX "pg_catalog"."pg_operator_oid_index"
GO
DROP INDEX "pg_catalog"."pg_opclass_oid_index"
GO
DROP INDEX "pg_catalog"."pg_opclass_am_name_nsp_index"
GO
DROP INDEX "pg_catalog"."pg_namespace_oid_index"
GO
DROP INDEX "pg_catalog"."pg_namespace_nspname_index"
GO
DROP INDEX "pg_catalog"."pg_largeobject_loid_pn_index"
GO
DROP INDEX "pg_catalog"."pg_language_oid_index"
GO
DROP INDEX "pg_catalog"."pg_language_name_index"
GO
DROP INDEX "pg_catalog"."pg_inherits_relid_seqno_index"
GO
DROP INDEX "pg_catalog"."pg_index_indrelid_index"
GO
DROP INDEX "pg_catalog"."pg_index_indexrelid_index"
GO
DROP INDEX "pg_catalog"."pg_enum_typid_label_index"
GO
DROP INDEX "pg_catalog"."pg_enum_oid_index"
GO
DROP INDEX "pg_catalog"."pg_description_o_c_o_index"
GO
DROP INDEX "pg_catalog"."pg_depend_reference_index"
GO
DROP INDEX "pg_catalog"."pg_depend_depender_index"
GO
DROP INDEX "pg_catalog"."pg_database_oid_index"
GO
DROP INDEX "pg_catalog"."pg_database_datname_index"
GO
DROP INDEX "pg_catalog"."pg_conversion_oid_index"
GO
DROP INDEX "pg_catalog"."pg_conversion_name_nsp_index"
GO
DROP INDEX "pg_catalog"."pg_conversion_default_index"
GO
DROP INDEX "pg_catalog"."pg_constraint_oid_index"
GO
DROP INDEX "pg_catalog"."pg_constraint_contypid_index"
GO
DROP INDEX "pg_catalog"."pg_constraint_conrelid_index"
GO
DROP INDEX "pg_catalog"."pg_constraint_conname_nsp_index"
GO
DROP INDEX "pg_catalog"."pg_class_relname_nsp_index"
GO
DROP INDEX "pg_catalog"."pg_class_oid_index"
GO
DROP INDEX "pg_catalog"."pg_cast_source_target_index"
GO
DROP INDEX "pg_catalog"."pg_cast_oid_index"
GO
DROP INDEX "pg_catalog"."pg_autovacuum_vacrelid_index"
GO
DROP INDEX "pg_catalog"."pg_authid_rolname_index"
GO
DROP INDEX "pg_catalog"."pg_authid_oid_index"
GO
DROP INDEX "pg_catalog"."pg_auth_members_role_member_index"
GO
DROP INDEX "pg_catalog"."pg_auth_members_member_role_index"
GO
DROP INDEX "pg_catalog"."pg_attribute_relid_attnum_index"
GO
DROP INDEX "pg_catalog"."pg_attribute_relid_attnam_index"
GO
DROP INDEX "pg_catalog"."pg_attrdef_oid_index"
GO
DROP INDEX "pg_catalog"."pg_attrdef_adrelid_adnum_index"
GO
DROP INDEX "pg_catalog"."pg_amproc_oid_index"
GO
DROP INDEX "pg_catalog"."pg_amproc_fam_proc_index"
GO
DROP INDEX "pg_catalog"."pg_amop_opr_fam_index"
GO
DROP INDEX "pg_catalog"."pg_amop_oid_index"
GO
DROP INDEX "pg_catalog"."pg_amop_fam_strat_index"
GO
DROP INDEX "pg_catalog"."pg_am_oid_index"
GO
DROP INDEX "pg_catalog"."pg_am_name_index"
GO
DROP INDEX "pg_catalog"."pg_aggregate_fnoid_index"
GO
DROP TABLE "public"."unidad_educativa"
GO
DROP TABLE "public"."tipo_materia"
GO
DROP TABLE "public"."seccion"
GO
DROP TABLE "public"."rol_persona"
GO
DROP TABLE "public"."rol_opcion"
GO
DROP TABLE "public"."rol"
GO
DROP TABLE "public"."respuesta"
GO
DROP TABLE "public"."registro"
GO
DROP TABLE "public"."region"
GO
DROP TABLE "public"."recurso_materia"
GO
DROP TABLE "public"."recurso_keyword"
GO
DROP TABLE "public"."recurso_herramienta_evaluacion"
GO
DROP TABLE "public"."recurso_herramienta_clase"
GO
DROP TABLE "public"."recurso"
GO
DROP TABLE "public"."pregunta"
GO
DROP TABLE "public"."persona_grupo"
GO
DROP TABLE "public"."persona"
GO
DROP TABLE "public"."periodo"
GO
DROP TABLE "public"."paralelo"
GO
DROP TABLE "public"."pais"
GO
DROP TABLE "public"."opcion_respuesta"
GO
DROP TABLE "public"."opcion_pregunta"
GO
DROP TABLE "public"."opcion"
GO
DROP TABLE "public"."nota"
GO
DROP TABLE "public"."mes_setup"
GO
DROP TABLE "public"."mes_clase"
GO
DROP TABLE "public"."matricula"
GO
DROP TABLE "public"."materia"
GO
DROP TABLE "public"."historico_materia"
GO
DROP TABLE "public"."historico_academico_mensual"
GO
DROP TABLE "public"."historico_academico_anual"
GO
DROP TABLE "public"."herramienta_evaluacion"
GO
DROP TABLE "public"."herramienta_clase_agrupacion"
GO
DROP TABLE "public"."herramienta_clase"
GO
DROP TABLE "public"."grupo"
GO
DROP TABLE "public"."estudiante_representante"
GO
DROP TABLE "public"."dia_festivo"
GO
DROP TABLE "public"."detalle_catalogo"
GO
DROP TABLE "public"."datos_representante"
GO
DROP TABLE "public"."datos_estudiante"
GO
DROP TABLE "public"."datos_empleado_ue"
GO
DROP TABLE "public"."curso_materia"
GO
DROP TABLE "public"."curso"
GO
DROP TABLE "public"."continuidad_seccion"
GO
DROP TABLE "public"."continuidad_materia"
GO
DROP TABLE "public"."contenido"
GO
DROP TABLE "public"."configuracion_sistema"
GO
DROP TABLE "public"."clase"
GO
DROP TABLE "public"."catalogo_tipo"
GO
DROP SEQUENCE "public"."seq_opcion"
GO
DROP SEQUENCE "public"."seq_unidad_educativa"
GO
DROP SEQUENCE "public"."seq_tipo_materia"
GO
DROP SEQUENCE "public"."seq_seccion"
GO
DROP SEQUENCE "public"."seq_rol"
GO
DROP SEQUENCE "public"."seq_respuesta"
GO
DROP SEQUENCE "public"."seq_registro"
GO
DROP SEQUENCE "public"."seq_region"
GO
DROP SEQUENCE "public"."seq_recurso"
GO
DROP SEQUENCE "public"."seq_pregunta"
GO
DROP SEQUENCE "public"."seq_persona"
GO
DROP SEQUENCE "public"."seq_periodo"
GO
DROP SEQUENCE "public"."seq_paralelo"
GO
DROP SEQUENCE "public"."seq_pais"
GO
DROP SEQUENCE "public"."seq_opcion_respuesta"
GO
DROP SEQUENCE "public"."seq_opcion_pregunta"
GO
DROP SEQUENCE "public"."seq_nota"
GO
DROP SEQUENCE "public"."seq_mes_setup"
GO
DROP SEQUENCE "public"."seq_matricula"
GO
DROP SEQUENCE "public"."seq_materia"
GO
DROP SEQUENCE "public"."seq_historico_materia"
GO
DROP SEQUENCE "public"."seq_historico_academico_mensual"
GO
DROP SEQUENCE "public"."seq_historico_academico_anual"
GO
DROP SEQUENCE "public"."seq_herramienta_evaluacion"
GO
DROP SEQUENCE "public"."seq_herramienta_clase_agrupacion"
GO
DROP SEQUENCE "public"."seq_herramienta_clase"
GO
DROP SEQUENCE "public"."seq_grupo"
GO
DROP SEQUENCE "public"."seq_dia_festivo"
GO
DROP SEQUENCE "public"."seq_detalle_catalogo"
GO
DROP SEQUENCE "public"."seq_curso"
GO
DROP SEQUENCE "public"."seq_contenido"
GO
DROP SEQUENCE "public"."seq_clase"
GO
DROP SEQUENCE "public"."seq_catalogo_tipo"
GO

CREATE SEQUENCE "public"."seq_catalogo_tipo"
GO
CREATE SEQUENCE "public"."seq_clase"
GO
CREATE SEQUENCE "public"."seq_contenido"
GO
CREATE SEQUENCE "public"."seq_curso"
GO
CREATE SEQUENCE "public"."seq_detalle_catalogo"
GO
CREATE SEQUENCE "public"."seq_dia_festivo"
GO
CREATE SEQUENCE "public"."seq_grupo"
GO
CREATE SEQUENCE "public"."seq_herramienta_clase"
GO
CREATE SEQUENCE "public"."seq_herramienta_clase_agrupacion"
GO
CREATE SEQUENCE "public"."seq_herramienta_evaluacion"
GO
CREATE SEQUENCE "public"."seq_historico_academico_anual"
GO
CREATE SEQUENCE "public"."seq_historico_academico_mensual"
GO
CREATE SEQUENCE "public"."seq_historico_materia"
GO
CREATE SEQUENCE "public"."seq_materia"
GO
CREATE SEQUENCE "public"."seq_matricula"
GO
CREATE SEQUENCE "public"."seq_mes_setup"
GO
CREATE SEQUENCE "public"."seq_nota"
GO
CREATE SEQUENCE "public"."seq_opcion_pregunta"
GO
CREATE SEQUENCE "public"."seq_opcion_respuesta"
GO
CREATE SEQUENCE "public"."seq_pais"
GO
CREATE SEQUENCE "public"."seq_paralelo"
GO
CREATE SEQUENCE "public"."seq_periodo"
GO
CREATE SEQUENCE "public"."seq_persona"
GO
CREATE SEQUENCE "public"."seq_pregunta"
GO
CREATE SEQUENCE "public"."seq_recurso"
GO
CREATE SEQUENCE "public"."seq_region"
GO
CREATE SEQUENCE "public"."seq_registro"
GO
CREATE SEQUENCE "public"."seq_respuesta"
GO
CREATE SEQUENCE "public"."seq_rol"
GO
CREATE SEQUENCE "public"."seq_seccion"
GO
CREATE SEQUENCE "public"."seq_tipo_materia"
GO
CREATE SEQUENCE "public"."seq_unidad_educativa"
GO
CREATE SEQUENCE "public"."seq_opcion"
GO
CREATE TABLE "public"."catalogo_tipo"  ( 
	"id_cat_tip"    	int4 NOT NULL,
	"cat_id_cat_tip"	int4 NULL,
	"nombre"        	varchar(64) NOT NULL,
	"descripcion"   	varchar(256) NULL,
	PRIMARY KEY("id_cat_tip")
)
GO
CREATE TABLE "public"."clase"  ( 
	"id_clase"   	int4 NOT NULL,
	"id_paralelo"	int4 NULL,
	"id_per"     	int4 NOT NULL,
	"id_persona" 	int4 NOT NULL,
	"id_materia" 	int4 NOT NULL,
	"nombre"     	varchar(32) NOT NULL,
	PRIMARY KEY("id_clase")
)
GO
CREATE TABLE "public"."configuracion_sistema"  ( 
	"id_persona"    	int4 NOT NULL,
	"e_mail_sistema"	varchar(64) NULL,
	PRIMARY KEY("id_persona")
)
GO
CREATE TABLE "public"."contenido"  ( 
	"id_contenido"	int4 NOT NULL,
	"id_mes_setup"	int4 NOT NULL,
	"id_materia"  	int4 NOT NULL,
	"contenido"   	varchar(2048) NOT NULL,
	"activo"      	bool NOT NULL,
	PRIMARY KEY("id_contenido")
)
GO
CREATE TABLE "public"."continuidad_materia"  ( 
	"id_materia_ante"	int4 NOT NULL,
	"id_materia_sig" 	int4 NOT NULL,
	PRIMARY KEY("id_materia_ante","id_materia_sig")
)
GO
CREATE TABLE "public"."continuidad_seccion"  ( 
	"id_seccion"    	int4 NOT NULL,
	"sec_id_seccion"	int4 NOT NULL,
	PRIMARY KEY("id_seccion","sec_id_seccion")
)
GO
CREATE TABLE "public"."curso"  ( 
	"id_curso"                	int4 NOT NULL,
	"id_seccion"              	int4 NOT NULL,
	"id_curso_ante"           	int4 NULL,
	"id_curso_base"           	int4 NULL,
	"nombre"                  	varchar(64) NOT NULL,
	"descripcion"             	varchar(256) NULL,
	"activo"                  	bool NOT NULL,
	"cupo"                    	int2 NOT NULL,
	"estudiantes_por_paralelo"	int2 NULL,
	PRIMARY KEY("id_curso")
)
GO
CREATE TABLE "public"."curso_materia"  ( 
	"id_curso"  	int4 NOT NULL,
	"id_materia"	int4 NOT NULL,
	PRIMARY KEY("id_curso","id_materia")
)
GO
CREATE TABLE "public"."datos_empleado_ue"  ( 
	"id_persona"             	int4 NOT NULL,
	"id_ue"                  	int4 NOT NULL,
	"institucion_procedencia"	varchar(64) NULL,
	"experiencia_previa"     	varchar(512) NULL,
	"tiempo_"                	int4 NULL,
	"titulo"                 	varchar(64) NULL,
	"activo"                 	bool NOT NULL,
	"fecha_ingreso"          	date NOT NULL,
	"fecha_salida"           	date NULL,
	PRIMARY KEY("id_persona","id_ue")
)
GO
CREATE TABLE "public"."datos_estudiante"  ( 
	"id_persona"        	int4 NOT NULL,
	"observacion_medica"	varchar(512) NULL,
	"otra_insti_proce"  	varchar(64) NULL,
	PRIMARY KEY("id_persona")
)
GO
CREATE TABLE "public"."datos_representante"  ( 
	"id_persona"	int4 NOT NULL,
	PRIMARY KEY("id_persona")
)
GO
CREATE TABLE "public"."detalle_catalogo"  ( 
	"id_det_cat" 	int4 NOT NULL,
	"id_cat_tip" 	int4 NOT NULL,
	"nemonico"   	varchar(6) NULL,
	"nombre"     	varchar(64) NOT NULL,
	"descripcion"	varchar(256) NULL,
	"activo"     	bool NOT NULL,
	PRIMARY KEY("id_det_cat")
)
GO
CREATE TABLE "public"."dia_festivo"  ( 
	"id_dia_fest"	int4 NOT NULL,
	"id_per"     	int4 NOT NULL,
	"nombre"     	varchar(64) NOT NULL,
	"descripcion"	varchar(256) NULL,
	"fecha"      	date NOT NULL,
	PRIMARY KEY("id_dia_fest")
)
GO
CREATE TABLE "public"."estudiante_representante"  ( 
	"id_persona"    	int4 NOT NULL,
	"per_id_persona"	int4 NOT NULL,
	"id_det_cat"    	int4 NOT NULL,
	"activo"        	bool NOT NULL,
	PRIMARY KEY("id_persona","per_id_persona")
)
GO
CREATE TABLE "public"."grupo"  ( 
	"id_grupo"      	int4 NOT NULL,
	"id_persona"    	int4 NOT NULL,
	"id_her_cla"    	int4 NULL,
	"nombre"        	varchar(64) NOT NULL,
	"descripcion"   	varchar(256) NULL,
	"fecha_creacion"	date NOT NULL,
	"activo"        	bool NOT NULL,
	PRIMARY KEY("id_grupo")
)
GO
CREATE TABLE "public"."herramienta_clase"  ( 
	"id_her_cla"        	int4 NOT NULL,
	"id_her_cla_agr"    	int4 NULL,
	"id_her_eva"        	int4 NOT NULL,
	"id_mes_setup"      	int4 NOT NULL,
	"id_clase"          	int4 NOT NULL,
	"fecha_presentacion"	date NOT NULL,
	"generico"          	bool NOT NULL,
	"porcentaje"        	numeric NOT NULL,
	PRIMARY KEY("id_her_cla")
)
GO
CREATE TABLE "public"."herramienta_clase_agrupacion"  ( 
	"id_her_cla_agr"	int4 NOT NULL,
	"id_seccion"    	int4 NULL,
	"activo"        	bool NOT NULL,
	"nombre"        	varchar(64) NOT NULL,
	"descripcion"   	varchar(256) NULL,
	"generico"      	bool NOT NULL,
	"porcentaje"    	numeric NOT NULL,
	PRIMARY KEY("id_her_cla_agr")
)
GO
CREATE TABLE "public"."herramienta_evaluacion"  ( 
	"id_her_eva"    	int4 NOT NULL,
	"activo"        	bool NOT NULL,
	"fecha_creacion"	date NOT NULL,
	"tipo_her_eva"  	varchar(12) NOT NULL,
	"nombre"        	varchar(64) NOT NULL,
	"descripcion"   	varchar(256) NULL,
	"explicacion"   	varchar(2048) NOT NULL,
	PRIMARY KEY("id_her_eva")
)
GO
CREATE TABLE "public"."historico_academico_anual"  ( 
	"id_haa"              	int4 NOT NULL,
	"id_persona"          	int4 NOT NULL,
	"per_id_persona"      	int4 NULL,
	"id_materia"          	int4 NOT NULL,
	"id_per"              	int4 NOT NULL,
	"nota_general"        	numeric NOT NULL,
	"nota_parcial1"       	numeric NULL,
	"cantidad_parciales"  	int2 NULL,
	"nota_parcial2"       	numeric NULL,
	"nota_parcial3"       	numeric NULL,
	"nota_parcial4"       	numeric NULL,
	"nota_parcial5"       	numeric NULL,
	"nota_parcial6"       	numeric NULL,
	"nota_parcial7"       	numeric NULL,
	"nota_parcial8"       	numeric NULL,
	"nota_parcial9"       	numeric NULL,
	"nota_parcial10"      	numeric NULL,
	"activo"              	bool NOT NULL,
	"profesor"            	varchar(256) NOT NULL,
	"porcentaje_parcial5" 	numeric NULL,
	"porcentaje_parcial4" 	numeric NULL,
	"porcentaje_parcial3" 	numeric NULL,
	"porcentaje_parcial2" 	numeric NULL,
	"porcentaje_parcial1" 	numeric NULL,
	"porcentaje_parcial6" 	numeric NULL,
	"porcentaje_parcial7" 	numeric NULL,
	"porcentaje_parcial8" 	numeric NULL,
	"porcentaje_parcial9" 	numeric NULL,
	"porcentaje_parcial10"	numeric NULL,
	PRIMARY KEY("id_haa")
)
GO
CREATE TABLE "public"."historico_academico_mensual"  ( 
	"id_ham"              	int4 NOT NULL,
	"id_persona"          	int4 NOT NULL,
	"id_per"              	int4 NOT NULL,
	"per_id_persona"      	int4 NULL,
	"id_mes_setup"        	int4 NOT NULL,
	"id_materia"          	int4 NOT NULL,
	"nota_general"        	numeric NOT NULL,
	"ranking_clase"       	int2 NOT NULL,
	"ranking_curso"       	int2 NOT NULL,
	"catidad_parciales"   	int2 NULL,
	"activo"              	bool NULL,
	"porcentaje_parcial1" 	numeric NULL,
	"porcentaje_parcial2" 	numeric NULL,
	"porcentaje_parcial3" 	numeric NULL,
	"porcentaje_parcial4" 	numeric NULL,
	"porcentaje_parcial5" 	numeric NULL,
	"porcentaje_parcial6" 	numeric NULL,
	"porcentaje_parcial7" 	numeric NULL,
	"porcentaje_parcial8" 	numeric NULL,
	"porcentaje_parcial9" 	numeric NULL,
	"porcentaje_parcial10"	numeric NULL,
	"nota_parcial1"       	numeric NULL,
	"nota_parcial2"       	numeric NULL,
	"nota_parcial3"       	numeric NULL,
	"nota_parcial4"       	numeric NULL,
	"nota_parcial5"       	numeric NULL,
	"nota_parcial6"       	numeric NULL,
	"nota_parcial7"       	numeric NULL,
	"nota_parcial8"       	numeric NULL,
	"nota_parcial9"       	numeric NULL,
	"nota_parcial10"      	numeric NULL,
	"profesor"            	varchar(256) NOT NULL,
	PRIMARY KEY("id_ham")
)
GO
CREATE TABLE "public"."historico_materia"  ( 
	"id_hm"                 	int4 NOT NULL,
	"id_materia"            	int4 NOT NULL,
	"id_curso"              	int4 NOT NULL,
	"id_persona"            	int4 NOT NULL,
	"id_per"                	int4 NOT NULL,
	"numero_estudiantes"    	int2 NOT NULL,
	"evaluacion_director"   	varchar(12) NULL,
	"evaluacion_estudiantes"	varchar(12) NULL,
	"termino"               	bool NULL,
	"empezo"                	bool NULL,
	PRIMARY KEY("id_hm")
)
GO
CREATE TABLE "public"."materia"  ( 
	"id_materia"     	int4 NOT NULL,
	"id_ue"          	int4 NULL,
	"id_materia_base"	int4 NULL,
	"id_tip_materia" 	int4 NULL,
	"nombre"         	varchar(64) NOT NULL,
	"descripcion"    	varchar(256) NULL,
	"contenidos"     	varchar(2048) NULL,
	"activo"         	bool NOT NULL,
	PRIMARY KEY("id_materia")
)
GO
CREATE TABLE "public"."matricula"  ( 
	"id_matricula"   	int4 NOT NULL,
	"id_per"         	int4 NOT NULL,
	"id_paralelo"    	int4 NOT NULL,
	"id_persona"     	int4 NOT NULL,
	"fecha_matricula"	date NOT NULL,
	PRIMARY KEY("id_matricula")
)
GO
CREATE TABLE "public"."mes_clase"  ( 
	"id_mes_setup"	int4 NOT NULL,
	"id_clase"    	int4 NOT NULL,
	PRIMARY KEY("id_clase","id_mes_setup")
)
GO
CREATE TABLE "public"."mes_setup"  ( 
	"id_mes_setup"      	int4 NOT NULL,
	"id_seccion"        	int4 NULL,
	"fecha_inicio"      	date NOT NULL,
	"fecha_fin"         	date NOT NULL,
	"fecha_apertura_sis"	date NOT NULL,
	"fecha_cierre_sis"  	date NOT NULL,
	"activo"            	bool NOT NULL,
	PRIMARY KEY("id_mes_setup")
)
GO
CREATE TABLE "public"."nota"  ( 
	"id_nota"           	int4 NOT NULL,
	"id_matricula"      	int4 NOT NULL,
	"id_her_cla"        	int4 NOT NULL,
	"nota"              	numeric NULL,
	"nota_bool"         	bool NULL,
	"fecha_creacion"    	date NOT NULL,
	"fecha_modificacion"	date NOT NULL,
	PRIMARY KEY("id_nota")
)
GO
CREATE TABLE "public"."opcion"  ( 
	"nombre"         	varchar(64) NOT NULL,
	"id_opcion"      	int4 NOT NULL,
	"descripcion"    	varchar(256) NULL,
	"url"            	varchar(512) NOT NULL,
	"id_opcion_padre"	int4 NULL,
	"tipo"           	int4 NULL,
	"tipo_desc"      	varchar(256) NULL,
	PRIMARY KEY("id_opcion")
)
GO
CREATE TABLE "public"."opcion_pregunta"  ( 
	"id_opcion_pregunta"	int4 NOT NULL,
	"id_pregunta"       	int4 NOT NULL,
	"etiqueta"          	varchar(128) NOT NULL,
	"correcto_bool"     	bool NULL,
	"correcto_numero"   	numeric NULL,
	"correcto_texto"    	varchar(128) NULL,
	PRIMARY KEY("id_opcion_pregunta")
)
GO
CREATE TABLE "public"."opcion_respuesta"  ( 
	"id_opcion_respuesta"  	int4 NOT NULL,
	"id_respuesta"         	int4 NOT NULL,
	"id_opcion_pregunta"   	int4 NOT NULL,
	"respuesta_bool"       	bool NULL,
	"respuesta_numero"     	numeric NULL,
	"respuesta_texto"      	varchar(128) NULL,
	"respuesta_observacion"	varchar(1024) NULL,
	PRIMARY KEY("id_opcion_respuesta")
)
GO
CREATE TABLE "public"."pais"  ( 
	"id_pai"     	int4 NOT NULL,
	"nombre"     	varchar(64) NOT NULL,
	"descripcion"	varchar(256) NULL,
	"observacion"	varchar(512) NULL,
	"nemonico"   	varchar(6) NULL,
	"activo"     	bool NOT NULL,
	PRIMARY KEY("id_pai")
)
GO
CREATE TABLE "public"."paralelo"  ( 
	"id_paralelo"             	int4 NOT NULL,
	"id_curso"                	int4 NOT NULL,
	"activo"                  	bool NOT NULL,
	"observacion"             	varchar(512) NULL,
	"estudiantes_por_paralelo"	int2 NULL,
	PRIMARY KEY("id_paralelo")
)
GO
CREATE TABLE "public"."periodo"  ( 
	"id_per"     	int4 NOT NULL,
	"id_reg"     	int4 NULL,
	"nombre"     	varchar(64) NULL,
	"descripcion"	varchar(256) NULL,
	"observacion"	varchar(512) NULL,
	"activo"     	bool NOT NULL,
	PRIMARY KEY("id_per")
)
GO
CREATE TABLE "public"."persona"  ( 
	"id_persona"         	int4 NOT NULL,
	"id_det_cat"         	int4 NOT NULL,
	"nombres"            	varchar(128) NOT NULL,
	"apellidos"          	varchar(128) NOT NULL,
	"ci_pasaporte"       	varchar(10) NULL,
	"fecha_nacimiento"   	date NULL,
	"usuario"            	varchar(64) NOT NULL,
	"contrasena"         	varchar(64) NOT NULL,
	"activo"             	bool NOT NULL,
	"perfil"             	varchar(32) NOT NULL,
	"telefono_contacto_1"	varchar(12) NULL,
	"telefono_contacto_2"	varchar(12) NULL,
	"e_mail_personal"    	varchar(64) NULL,
	PRIMARY KEY("id_persona")
)
GO
CREATE TABLE "public"."persona_grupo"  ( 
	"id_grupo"  	int4 NOT NULL,
	"id_persona"	int4 NOT NULL,
	PRIMARY KEY("id_grupo","id_persona")
)
GO
CREATE TABLE "public"."pregunta"  ( 
	"id_pregunta"        	int4 NOT NULL,
	"id_her_eva"         	int4 NOT NULL,
	"orden"              	int2 NOT NULL,
	"cantidad_opciones"  	int2 NULL,
	"tipo_pregunta"      	varchar(12) NOT NULL,
	"descripcion"        	varchar(256) NOT NULL,
	"explicacion"        	varchar(2048) NULL,
	"cantidad_respuestas"	int2 NULL,
	PRIMARY KEY("id_pregunta")
)
GO
CREATE TABLE "public"."recurso"  ( 
	"id_recurso"       	int4 NOT NULL,
	"id_her_eva"       	int4 NULL,
	"id_det_cat"       	int4 NOT NULL,
	"nombre"           	varchar(64) NOT NULL,
	"descripcion"      	varchar(256) NULL,
	"descripcion_larga"	varchar(2048) NULL,
	"activo"           	bool NOT NULL,
	"url"              	varchar(512) NULL,
	PRIMARY KEY("id_recurso")
)
GO
CREATE TABLE "public"."recurso_herramienta_clase"  ( 
	"id_her_cla"	int4 NOT NULL,
	"id_recurso"	int4 NOT NULL,
	PRIMARY KEY("id_her_cla","id_recurso")
)
GO
CREATE TABLE "public"."recurso_herramienta_evaluacion"  ( 
	"id_recurso"	int4 NOT NULL,
	"id_her_eva"	int4 NOT NULL,
	PRIMARY KEY("id_her_eva","id_recurso")
)
GO
CREATE TABLE "public"."recurso_keyword"  ( 
	"id_recurso"	int4 NOT NULL,
	"id_det_cat"	int4 NOT NULL,
	PRIMARY KEY("id_det_cat","id_recurso")
)
GO
CREATE TABLE "public"."recurso_materia"  ( 
	"id_materia"	int4 NOT NULL,
	"id_recurso"	int4 NOT NULL,
	PRIMARY KEY("id_materia","id_recurso")
)
GO
CREATE TABLE "public"."region"  ( 
	"id_reg"     	int4 NOT NULL,
	"id_pai"     	int4 NOT NULL,
	"nombre"     	varchar(64) NOT NULL,
	"descripcion"	varchar(256) NULL,
	"observacion"	varchar(512) NULL,
	"nemonico"   	varchar(6) NULL,
	"activo"     	bool NOT NULL,
	PRIMARY KEY("id_reg")
)
GO
CREATE TABLE "public"."registro"  ( 
	"id_registro"         	int4 NOT NULL,
	"id_mes_setup"        	int4 NOT NULL,
	"id_clase"            	int4 NOT NULL,
	"fecha_registro"      	date NOT NULL,
	"descripcion_registro"	varchar(1024) NOT NULL,
	PRIMARY KEY("id_registro")
)
GO
CREATE TABLE "public"."respuesta"  ( 
	"id_respuesta"         	int4 NOT NULL,
	"id_pregunta"          	int4 NOT NULL,
	"id_nota"              	int4 NOT NULL,
	"respuesta_bool"       	bool NULL,
	"respuesta_texto"      	varchar(128) NULL,
	"respuesta_numero"     	numeric NULL,
	"respuesta_observacion"	varchar(1024) NULL,
	PRIMARY KEY("id_respuesta")
)
GO
CREATE TABLE "public"."rol"  ( 
	"id_rol"	int4 NOT NULL,
	"rol"   	varchar(64) NOT NULL,
	"id_ue" 	int4 NOT NULL,
	PRIMARY KEY("id_rol")
)
GO
CREATE TABLE "public"."rol_opcion"  ( 
	"id_opcion"	int4 NOT NULL,
	"id_rol"   	int4 NOT NULL,
	PRIMARY KEY("id_opcion","id_rol")
)
GO
CREATE TABLE "public"."rol_persona"  ( 
	"id_rol"    	int4 NOT NULL,
	"id_persona"	int4 NOT NULL,
	PRIMARY KEY("id_persona","id_rol")
)
GO
CREATE TABLE "public"."seccion"  ( 
	"id_seccion"           	int4 NOT NULL,
	"id_ue"                	int4 NULL,
	"id_seccion_padre"     	int4 NULL,
	"id_seccion_base"      	int4 NULL,
	"nombre"               	varchar(64) NULL,
	"descripcion"          	varchar(256) NULL,
	"activo"               	bool NOT NULL,
	"minimo_aprobacion"    	numeric NOT NULL,
	"nombre_division"      	varchar(64) NULL,
	"cantidad_division"    	int2 NULL,
	"nombre_subdivision"   	varchar(64) NULL,
	"cantidad_subdivision" 	int2 NULL,
	"estudiantes_por_curso"	int2 NULL,
	"implementacion"       	bool NOT NULL,
	PRIMARY KEY("id_seccion")
)
GO
CREATE TABLE "public"."tipo_materia"  ( 
	"id_tip_materia"	int4 NOT NULL,
	"nombre"        	varchar(64) NOT NULL,
	"descripcion"   	varchar(256) NULL,
	"activo"        	bool NOT NULL,
	PRIMARY KEY("id_tip_materia")
)
GO
CREATE TABLE "public"."unidad_educativa"  ( 
	"id_ue"                	int4 NOT NULL,
	"id_reg"               	int4 NOT NULL,
	"nombre"               	varchar(64) NOT NULL,
	"slogan"               	varchar(256) NULL,
	"mision"               	varchar(256) NULL,
	"vision"               	varchar(256) NULL,
	"direccion"            	varchar(256) NULL,
	"telefono_1"           	varchar(12) NOT NULL,
	"telefono_3"           	varchar(12) NULL,
	"telefono_2"           	varchar(12) NULL,
	"nombre_contacto_adm"  	varchar(256) NOT NULL,
	"telefono_contacto_adm"	varchar(12) NOT NULL,
	"e_mail_contacto_adm"  	varchar(128) NULL,
	"descripcion"          	varchar(256) NULL,
	"activo"               	bool NOT NULL,
	"e_mail"               	varchar(128) NULL,
	"website"              	varchar(256) NULL,
	"director"             	varchar(128) NULL,
	"foto_escudo_dir"      	varchar(256) NULL,
	"foto_director_dir"    	varchar(256) NULL,
	"provincia"            	varchar(256) NOT NULL,
	"canton"               	varchar(256) NOT NULL,
	"parroquia"            	varchar(256) NOT NULL,
	"tipo_institucion"     	varchar(64) NOT NULL,
	PRIMARY KEY("id_ue")
)
GO
CREATE UNIQUE INDEX "pg_aggregate_fnoid_index"
	ON "pg_catalog"."pg_aggregate"("aggfnoid")
GO
CREATE UNIQUE INDEX "pg_am_name_index"
	ON "pg_catalog"."pg_am"("amname")
GO
CREATE UNIQUE INDEX "pg_am_oid_index"
	ON "pg_catalog"."pg_am"("oid")
GO
CREATE UNIQUE INDEX "pg_amop_fam_strat_index"
	ON "pg_catalog"."pg_amop"("amopfamily", "amoplefttype", "amoprighttype", "amopstrategy")
GO
CREATE UNIQUE INDEX "pg_amop_oid_index"
	ON "pg_catalog"."pg_amop"("oid")
GO
CREATE UNIQUE INDEX "pg_amop_opr_fam_index"
	ON "pg_catalog"."pg_amop"("amopopr", "amopfamily")
GO
CREATE UNIQUE INDEX "pg_amproc_fam_proc_index"
	ON "pg_catalog"."pg_amproc"("amprocfamily", "amproclefttype", "amprocrighttype", "amprocnum")
GO
CREATE UNIQUE INDEX "pg_amproc_oid_index"
	ON "pg_catalog"."pg_amproc"("oid")
GO
CREATE UNIQUE INDEX "pg_attrdef_adrelid_adnum_index"
	ON "pg_catalog"."pg_attrdef"("adrelid", "adnum")
GO
CREATE UNIQUE INDEX "pg_attrdef_oid_index"
	ON "pg_catalog"."pg_attrdef"("oid")
GO
CREATE UNIQUE INDEX "pg_attribute_relid_attnam_index"
	ON "pg_catalog"."pg_attribute"("attrelid", "attname")
GO
CREATE UNIQUE INDEX "pg_attribute_relid_attnum_index"
	ON "pg_catalog"."pg_attribute"("attrelid", "attnum")
GO
CREATE UNIQUE INDEX "pg_auth_members_member_role_index"
	ON "pg_catalog"."pg_auth_members"("member", "roleid")
GO
CREATE UNIQUE INDEX "pg_auth_members_role_member_index"
	ON "pg_catalog"."pg_auth_members"("roleid", "member")
GO
CREATE UNIQUE INDEX "pg_authid_oid_index"
	ON "pg_catalog"."pg_authid"("oid")
GO
CREATE UNIQUE INDEX "pg_authid_rolname_index"
	ON "pg_catalog"."pg_authid"("rolname")
GO
CREATE UNIQUE INDEX "pg_autovacuum_vacrelid_index"
	ON "pg_catalog"."pg_autovacuum"("vacrelid")
GO
CREATE UNIQUE INDEX "pg_cast_oid_index"
	ON "pg_catalog"."pg_cast"("oid")
GO
CREATE UNIQUE INDEX "pg_cast_source_target_index"
	ON "pg_catalog"."pg_cast"("castsource", "casttarget")
GO
CREATE UNIQUE INDEX "pg_class_oid_index"
	ON "pg_catalog"."pg_class"("oid")
GO
CREATE UNIQUE INDEX "pg_class_relname_nsp_index"
	ON "pg_catalog"."pg_class"("relname", "relnamespace")
GO
CREATE INDEX "pg_constraint_conname_nsp_index"
	ON "pg_catalog"."pg_constraint"("conname", "connamespace")
GO
CREATE INDEX "pg_constraint_conrelid_index"
	ON "pg_catalog"."pg_constraint"("conrelid")
GO
CREATE INDEX "pg_constraint_contypid_index"
	ON "pg_catalog"."pg_constraint"("contypid")
GO
CREATE UNIQUE INDEX "pg_constraint_oid_index"
	ON "pg_catalog"."pg_constraint"("oid")
GO
CREATE UNIQUE INDEX "pg_conversion_default_index"
	ON "pg_catalog"."pg_conversion"("connamespace", "conforencoding", "contoencoding", "oid")
GO
CREATE UNIQUE INDEX "pg_conversion_name_nsp_index"
	ON "pg_catalog"."pg_conversion"("conname", "connamespace")
GO
CREATE UNIQUE INDEX "pg_conversion_oid_index"
	ON "pg_catalog"."pg_conversion"("oid")
GO
CREATE UNIQUE INDEX "pg_database_datname_index"
	ON "pg_catalog"."pg_database"("datname")
GO
CREATE UNIQUE INDEX "pg_database_oid_index"
	ON "pg_catalog"."pg_database"("oid")
GO
CREATE INDEX "pg_depend_depender_index"
	ON "pg_catalog"."pg_depend"("classid", "objid", "objsubid")
GO
CREATE INDEX "pg_depend_reference_index"
	ON "pg_catalog"."pg_depend"("refclassid", "refobjid", "refobjsubid")
GO
CREATE UNIQUE INDEX "pg_description_o_c_o_index"
	ON "pg_catalog"."pg_description"("objoid", "classoid", "objsubid")
GO
CREATE UNIQUE INDEX "pg_enum_oid_index"
	ON "pg_catalog"."pg_enum"("oid")
GO
CREATE UNIQUE INDEX "pg_enum_typid_label_index"
	ON "pg_catalog"."pg_enum"("enumtypid", "enumlabel")
GO
CREATE UNIQUE INDEX "pg_index_indexrelid_index"
	ON "pg_catalog"."pg_index"("indexrelid")
GO
CREATE INDEX "pg_index_indrelid_index"
	ON "pg_catalog"."pg_index"("indrelid")
GO
CREATE UNIQUE INDEX "pg_inherits_relid_seqno_index"
	ON "pg_catalog"."pg_inherits"("inhrelid", "inhseqno")
GO
CREATE UNIQUE INDEX "pg_language_name_index"
	ON "pg_catalog"."pg_language"("lanname")
GO
CREATE UNIQUE INDEX "pg_language_oid_index"
	ON "pg_catalog"."pg_language"("oid")
GO
CREATE UNIQUE INDEX "pg_largeobject_loid_pn_index"
	ON "pg_catalog"."pg_largeobject"("loid", "pageno")
GO
CREATE UNIQUE INDEX "pg_namespace_nspname_index"
	ON "pg_catalog"."pg_namespace"("nspname")
GO
CREATE UNIQUE INDEX "pg_namespace_oid_index"
	ON "pg_catalog"."pg_namespace"("oid")
GO
CREATE UNIQUE INDEX "pg_opclass_am_name_nsp_index"
	ON "pg_catalog"."pg_opclass"("opcmethod", "opcname", "opcnamespace")
GO
CREATE UNIQUE INDEX "pg_opclass_oid_index"
	ON "pg_catalog"."pg_opclass"("oid")
GO
CREATE UNIQUE INDEX "pg_operator_oid_index"
	ON "pg_catalog"."pg_operator"("oid")
GO
CREATE UNIQUE INDEX "pg_operator_oprname_l_r_n_index"
	ON "pg_catalog"."pg_operator"("oprname", "oprleft", "oprright", "oprnamespace")
GO
CREATE UNIQUE INDEX "pg_opfamily_am_name_nsp_index"
	ON "pg_catalog"."pg_opfamily"("opfmethod", "opfname", "opfnamespace")
GO
CREATE UNIQUE INDEX "pg_opfamily_oid_index"
	ON "pg_catalog"."pg_opfamily"("oid")
GO
CREATE UNIQUE INDEX "pg_pltemplate_name_index"
	ON "pg_catalog"."pg_pltemplate"("tmplname")
GO
CREATE UNIQUE INDEX "pg_proc_oid_index"
	ON "pg_catalog"."pg_proc"("oid")
GO
CREATE UNIQUE INDEX "pg_proc_proname_args_nsp_index"
	ON "pg_catalog"."pg_proc"("proname", "proargtypes", "pronamespace")
GO
CREATE UNIQUE INDEX "pg_rewrite_oid_index"
	ON "pg_catalog"."pg_rewrite"("oid")
GO
CREATE UNIQUE INDEX "pg_rewrite_rel_rulename_index"
	ON "pg_catalog"."pg_rewrite"("ev_class", "rulename")
GO
CREATE INDEX "pg_shdepend_depender_index"
	ON "pg_catalog"."pg_shdepend"("dbid", "classid", "objid")
GO
CREATE INDEX "pg_shdepend_reference_index"
	ON "pg_catalog"."pg_shdepend"("refclassid", "refobjid")
GO
CREATE UNIQUE INDEX "pg_shdescription_o_c_index"
	ON "pg_catalog"."pg_shdescription"("objoid", "classoid")
GO
CREATE UNIQUE INDEX "pg_statistic_relid_att_index"
	ON "pg_catalog"."pg_statistic"("starelid", "staattnum")
GO
CREATE UNIQUE INDEX "pg_tablespace_oid_index"
	ON "pg_catalog"."pg_tablespace"("oid")
GO
CREATE UNIQUE INDEX "pg_tablespace_spcname_index"
	ON "pg_catalog"."pg_tablespace"("spcname")
GO
CREATE UNIQUE INDEX "pg_trigger_oid_index"
	ON "pg_catalog"."pg_trigger"("oid")
GO
CREATE INDEX "pg_trigger_tgconstrname_index"
	ON "pg_catalog"."pg_trigger"("tgconstrname")
GO
CREATE UNIQUE INDEX "pg_trigger_tgrelid_tgname_index"
	ON "pg_catalog"."pg_trigger"("tgrelid", "tgname")
GO
CREATE UNIQUE INDEX "pg_ts_config_cfgname_index"
	ON "pg_catalog"."pg_ts_config"("cfgname", "cfgnamespace")
GO
CREATE UNIQUE INDEX "pg_ts_config_map_index"
	ON "pg_catalog"."pg_ts_config_map"("mapcfg", "maptokentype", "mapseqno")
GO
CREATE UNIQUE INDEX "pg_ts_config_oid_index"
	ON "pg_catalog"."pg_ts_config"("oid")
GO
CREATE UNIQUE INDEX "pg_ts_dict_dictname_index"
	ON "pg_catalog"."pg_ts_dict"("dictname", "dictnamespace")
GO
CREATE UNIQUE INDEX "pg_ts_dict_oid_index"
	ON "pg_catalog"."pg_ts_dict"("oid")
GO
CREATE UNIQUE INDEX "pg_ts_parser_oid_index"
	ON "pg_catalog"."pg_ts_parser"("oid")
GO
CREATE UNIQUE INDEX "pg_ts_parser_prsname_index"
	ON "pg_catalog"."pg_ts_parser"("prsname", "prsnamespace")
GO
CREATE UNIQUE INDEX "pg_ts_template_oid_index"
	ON "pg_catalog"."pg_ts_template"("oid")
GO
CREATE UNIQUE INDEX "pg_ts_template_tmplname_index"
	ON "pg_catalog"."pg_ts_template"("tmplname", "tmplnamespace")
GO
CREATE UNIQUE INDEX "pg_type_oid_index"
	ON "pg_catalog"."pg_type"("oid")
GO
CREATE UNIQUE INDEX "pg_type_typname_nsp_index"
	ON "pg_catalog"."pg_type"("typname", "typnamespace")
GO
CREATE UNIQUE INDEX "pg_toast_11429_index"
	ON "pg_toast"."pg_toast_11429"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_11434_index"
	ON "pg_toast"."pg_toast_11434"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_11439_index"
	ON "pg_toast"."pg_toast_11439"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_11444_index"
	ON "pg_toast"."pg_toast_11444"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_11449_index"
	ON "pg_toast"."pg_toast_11449"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_11454_index"
	ON "pg_toast"."pg_toast_11454"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_11459_index"
	ON "pg_toast"."pg_toast_11459"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_1255_index"
	ON "pg_toast"."pg_toast_1255"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_1260_index"
	ON "pg_toast"."pg_toast_1260"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_1262_index"
	ON "pg_toast"."pg_toast_1262"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_131154_index"
	ON "pg_toast"."pg_toast_131154"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_131182_index"
	ON "pg_toast"."pg_toast_131182"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_131190_index"
	ON "pg_toast"."pg_toast_131190"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_131223_index"
	ON "pg_toast"."pg_toast_131223"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_131231_index"
	ON "pg_toast"."pg_toast_131231"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_131239_index"
	ON "pg_toast"."pg_toast_131239"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_131247_index"
	ON "pg_toast"."pg_toast_131247"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_131255_index"
	ON "pg_toast"."pg_toast_131255"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_131268_index"
	ON "pg_toast"."pg_toast_131268"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_131291_index"
	ON "pg_toast"."pg_toast_131291"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_131299_index"
	ON "pg_toast"."pg_toast_131299"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_131307_index"
	ON "pg_toast"."pg_toast_131307"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_131315_index"
	ON "pg_toast"."pg_toast_131315"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_131323_index"
	ON "pg_toast"."pg_toast_131323"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_131331_index"
	ON "pg_toast"."pg_toast_131331"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_131339_index"
	ON "pg_toast"."pg_toast_131339"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_131347_index"
	ON "pg_toast"."pg_toast_131347"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_131360_index"
	ON "pg_toast"."pg_toast_131360"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_131368_index"
	ON "pg_toast"."pg_toast_131368"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_131396_index"
	ON "pg_toast"."pg_toast_131396"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_131404_index"
	ON "pg_toast"."pg_toast_131404"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_131412_index"
	ON "pg_toast"."pg_toast_131412"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_131435_index"
	ON "pg_toast"."pg_toast_131435"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_131448_index"
	ON "pg_toast"."pg_toast_131448"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_2396_index"
	ON "pg_toast"."pg_toast_2396"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_2604_index"
	ON "pg_toast"."pg_toast_2604"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_2606_index"
	ON "pg_toast"."pg_toast_2606"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_2609_index"
	ON "pg_toast"."pg_toast_2609"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_2618_index"
	ON "pg_toast"."pg_toast_2618"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "pg_toast_2619_index"
	ON "pg_toast"."pg_toast_2619"("chunk_id", "chunk_seq")
GO
CREATE UNIQUE INDEX "catalogo_tipo_pkey"
	ON "public"."catalogo_tipo"("id_cat_tip")
GO
CREATE UNIQUE INDEX "clase_pkey"
	ON "public"."clase"("id_clase")
GO
CREATE UNIQUE INDEX "configuracion_sistema_pkey"
	ON "public"."configuracion_sistema"("id_persona")
GO
CREATE UNIQUE INDEX "contenido_pkey"
	ON "public"."contenido"("id_contenido")
GO
CREATE UNIQUE INDEX "continuidad_materia_pkey"
	ON "public"."continuidad_materia"("id_materia_ante", "id_materia_sig")
GO
CREATE UNIQUE INDEX "continuidad_seccion_pkey"
	ON "public"."continuidad_seccion"("id_seccion", "sec_id_seccion")
GO
CREATE UNIQUE INDEX "curso_materia_pkey"
	ON "public"."curso_materia"("id_curso", "id_materia")
GO
CREATE UNIQUE INDEX "curso_pkey"
	ON "public"."curso"("id_curso")
GO
CREATE UNIQUE INDEX "datos_empleado_ue_pkey"
	ON "public"."datos_empleado_ue"("id_persona", "id_ue")
GO
CREATE UNIQUE INDEX "datos_estudiante_pkey"
	ON "public"."datos_estudiante"("id_persona")
GO
CREATE UNIQUE INDEX "datos_representante_pkey"
	ON "public"."datos_representante"("id_persona")
GO
CREATE UNIQUE INDEX "detalle_catalogo_pkey"
	ON "public"."detalle_catalogo"("id_det_cat")
GO
CREATE UNIQUE INDEX "dia_festivo_pkey"
	ON "public"."dia_festivo"("id_dia_fest")
GO
CREATE UNIQUE INDEX "estudiante_representante_pkey"
	ON "public"."estudiante_representante"("id_persona", "per_id_persona")
GO
CREATE UNIQUE INDEX "grupo_pkey"
	ON "public"."grupo"("id_grupo")
GO
CREATE UNIQUE INDEX "herramienta_clase_agrupacion_pkey"
	ON "public"."herramienta_clase_agrupacion"("id_her_cla_agr")
GO
CREATE UNIQUE INDEX "herramienta_clase_pkey"
	ON "public"."herramienta_clase"("id_her_cla")
GO
CREATE UNIQUE INDEX "herramienta_evaluacion_pkey"
	ON "public"."herramienta_evaluacion"("id_her_eva")
GO
CREATE UNIQUE INDEX "historico_academico_anual_pkey"
	ON "public"."historico_academico_anual"("id_haa")
GO
CREATE UNIQUE INDEX "historico_academico_mensual_pkey"
	ON "public"."historico_academico_mensual"("id_ham")
GO
CREATE UNIQUE INDEX "historico_materia_pkey"
	ON "public"."historico_materia"("id_hm")
GO
CREATE UNIQUE INDEX "materia_pkey"
	ON "public"."materia"("id_materia")
GO
CREATE UNIQUE INDEX "matricula_pkey"
	ON "public"."matricula"("id_matricula")
GO
CREATE UNIQUE INDEX "mes_clase_pkey"
	ON "public"."mes_clase"("id_mes_setup", "id_clase")
GO
CREATE UNIQUE INDEX "mes_setup_pkey"
	ON "public"."mes_setup"("id_mes_setup")
GO
CREATE UNIQUE INDEX "nota_pkey"
	ON "public"."nota"("id_nota")
GO
CREATE UNIQUE INDEX "opcion_pkey"
	ON "public"."opcion"("id_opcion")
GO
CREATE UNIQUE INDEX "opcion_pregunta_pkey"
	ON "public"."opcion_pregunta"("id_opcion_pregunta")
GO
CREATE UNIQUE INDEX "opcion_respuesta_pkey"
	ON "public"."opcion_respuesta"("id_opcion_respuesta")
GO
CREATE UNIQUE INDEX "pais_pkey"
	ON "public"."pais"("id_pai")
GO
CREATE UNIQUE INDEX "paralelo_pkey"
	ON "public"."paralelo"("id_paralelo")
GO
CREATE UNIQUE INDEX "periodo_pkey"
	ON "public"."periodo"("id_per")
GO
CREATE UNIQUE INDEX "persona_grupo_pkey"
	ON "public"."persona_grupo"("id_grupo", "id_persona")
GO
CREATE UNIQUE INDEX "persona_pkey"
	ON "public"."persona"("id_persona")
GO
CREATE UNIQUE INDEX "pregunta_pkey"
	ON "public"."pregunta"("id_pregunta")
GO
CREATE UNIQUE INDEX "recurso_herramienta_clase_pkey"
	ON "public"."recurso_herramienta_clase"("id_recurso", "id_her_cla")
GO
CREATE UNIQUE INDEX "recurso_herramienta_evaluacion_pkey"
	ON "public"."recurso_herramienta_evaluacion"("id_recurso", "id_her_eva")
GO
CREATE UNIQUE INDEX "recurso_keyword_pkey"
	ON "public"."recurso_keyword"("id_det_cat", "id_recurso")
GO
CREATE UNIQUE INDEX "recurso_materia_pkey"
	ON "public"."recurso_materia"("id_recurso", "id_materia")
GO
CREATE UNIQUE INDEX "recurso_pkey"
	ON "public"."recurso"("id_recurso")
GO
CREATE UNIQUE INDEX "region_pkey"
	ON "public"."region"("id_reg")
GO
CREATE UNIQUE INDEX "registro_pkey"
	ON "public"."registro"("id_registro")
GO
CREATE UNIQUE INDEX "respuesta_pkey"
	ON "public"."respuesta"("id_respuesta")
GO
CREATE UNIQUE INDEX "rol_opcion_pkey"
	ON "public"."rol_opcion"("id_opcion", "id_rol")
GO
CREATE UNIQUE INDEX "rol_persona_pkey"
	ON "public"."rol_persona"("id_rol", "id_persona")
GO
CREATE UNIQUE INDEX "rol_pkey"
	ON "public"."rol"("id_rol")
GO
CREATE UNIQUE INDEX "seccion_pkey"
	ON "public"."seccion"("id_seccion")
GO
CREATE UNIQUE INDEX "tipo_materia_pkey"
	ON "public"."tipo_materia"("id_tip_materia")
GO
CREATE UNIQUE INDEX "unidad_educativa_pkey"
	ON "public"."unidad_educativa"("id_ue")
GO

INSERT INTO "public"."catalogo_tipo"("id_cat_tip", "cat_id_cat_tip", "nombre", "descripcion")
  VALUES(1, NULL, 'ciudad', 'ciudad')
GO
INSERT INTO "public"."curso"("id_curso", "id_seccion", "id_curso_ante", "id_curso_base", "nombre", "descripcion", "activo", "cupo", "estudiantes_por_paralelo")
  VALUES(1, 1, NULL, NULL, '2do de basica', NULL, true, 100, NULL)
GO
INSERT INTO "public"."curso"("id_curso", "id_seccion", "id_curso_ante", "id_curso_base", "nombre", "descripcion", "activo", "cupo", "estudiantes_por_paralelo")
  VALUES(3, 1, NULL, NULL, '4to de basica', NULL, true, 100, NULL)
GO
INSERT INTO "public"."curso"("id_curso", "id_seccion", "id_curso_ante", "id_curso_base", "nombre", "descripcion", "activo", "cupo", "estudiantes_por_paralelo")
  VALUES(2, 1, NULL, NULL, '3ro de basica', NULL, true, 100, NULL)
GO
INSERT INTO "public"."curso"("id_curso", "id_seccion", "id_curso_ante", "id_curso_base", "nombre", "descripcion", "activo", "cupo", "estudiantes_por_paralelo")
  VALUES(4, 1, NULL, NULL, '5to de basica', NULL, true, 100, NULL)
GO
INSERT INTO "public"."curso"("id_curso", "id_seccion", "id_curso_ante", "id_curso_base", "nombre", "descripcion", "activo", "cupo", "estudiantes_por_paralelo")
  VALUES(6, 1, NULL, NULL, '7mo de basica', NULL, true, 100, NULL)
GO
INSERT INTO "public"."curso"("id_curso", "id_seccion", "id_curso_ante", "id_curso_base", "nombre", "descripcion", "activo", "cupo", "estudiantes_por_paralelo")
  VALUES(5, 1, NULL, NULL, '6to de basica', NULL, true, 100, NULL)
GO
INSERT INTO "public"."curso"("id_curso", "id_seccion", "id_curso_ante", "id_curso_base", "nombre", "descripcion", "activo", "cupo", "estudiantes_por_paralelo")
  VALUES(8, 3, NULL, NULL, '9no de basica', NULL, true, 100, NULL)
GO
INSERT INTO "public"."curso"("id_curso", "id_seccion", "id_curso_ante", "id_curso_base", "nombre", "descripcion", "activo", "cupo", "estudiantes_por_paralelo")
  VALUES(7, 3, NULL, NULL, '8vo de basica', NULL, true, 100, NULL)
GO
INSERT INTO "public"."curso"("id_curso", "id_seccion", "id_curso_ante", "id_curso_base", "nombre", "descripcion", "activo", "cupo", "estudiantes_por_paralelo")
  VALUES(9, 3, NULL, NULL, '10mo de basica', NULL, true, 100, NULL)
GO
INSERT INTO "public"."curso"("id_curso", "id_seccion", "id_curso_ante", "id_curso_base", "nombre", "descripcion", "activo", "cupo", "estudiantes_por_paralelo")
  VALUES(10, 5, NULL, NULL, '1ro diversificado', NULL, true, 100, NULL)
GO
INSERT INTO "public"."curso"("id_curso", "id_seccion", "id_curso_ante", "id_curso_base", "nombre", "descripcion", "activo", "cupo", "estudiantes_por_paralelo")
  VALUES(11, 5, NULL, NULL, '2do diversificado', NULL, true, 100, NULL)
GO
INSERT INTO "public"."curso"("id_curso", "id_seccion", "id_curso_ante", "id_curso_base", "nombre", "descripcion", "activo", "cupo", "estudiantes_por_paralelo")
  VALUES(12, 5, NULL, NULL, '3ro diversificado', NULL, true, 100, NULL)
GO
INSERT INTO "public"."curso"("id_curso", "id_seccion", "id_curso_ante", "id_curso_base", "nombre", "descripcion", "activo", "cupo", "estudiantes_por_paralelo")
  VALUES(13, 6, NULL, NULL, '1ro diversificado', NULL, true, 100, NULL)
GO
INSERT INTO "public"."curso"("id_curso", "id_seccion", "id_curso_ante", "id_curso_base", "nombre", "descripcion", "activo", "cupo", "estudiantes_por_paralelo")
  VALUES(15, 6, NULL, NULL, '3ro diversificado', NULL, true, 100, NULL)
GO
INSERT INTO "public"."curso"("id_curso", "id_seccion", "id_curso_ante", "id_curso_base", "nombre", "descripcion", "activo", "cupo", "estudiantes_por_paralelo")
  VALUES(14, 6, NULL, NULL, '2do diversificado', NULL, true, 100, NULL)
GO
INSERT INTO "public"."curso"("id_curso", "id_seccion", "id_curso_ante", "id_curso_base", "nombre", "descripcion", "activo", "cupo", "estudiantes_por_paralelo")
  VALUES(16, 7, NULL, 1, '2do de basica', NULL, true, 100, NULL)
GO
INSERT INTO "public"."curso"("id_curso", "id_seccion", "id_curso_ante", "id_curso_base", "nombre", "descripcion", "activo", "cupo", "estudiantes_por_paralelo")
  VALUES(30, 12, NULL, 15, '3ro diversificado', NULL, true, 100, NULL)
GO
INSERT INTO "public"."curso"("id_curso", "id_seccion", "id_curso_ante", "id_curso_base", "nombre", "descripcion", "activo", "cupo", "estudiantes_por_paralelo")
  VALUES(17, 7, NULL, 2, '4to de basica', NULL, true, 100, NULL)
GO
INSERT INTO "public"."curso"("id_curso", "id_seccion", "id_curso_ante", "id_curso_base", "nombre", "descripcion", "activo", "cupo", "estudiantes_por_paralelo")
  VALUES(20, 7, NULL, 5, '7mo de basica', NULL, true, 100, NULL)
GO
INSERT INTO "public"."curso"("id_curso", "id_seccion", "id_curso_ante", "id_curso_base", "nombre", "descripcion", "activo", "cupo", "estudiantes_por_paralelo")
  VALUES(21, 7, NULL, 6, '6to de basica', NULL, true, 100, NULL)
GO
INSERT INTO "public"."curso"("id_curso", "id_seccion", "id_curso_ante", "id_curso_base", "nombre", "descripcion", "activo", "cupo", "estudiantes_por_paralelo")
  VALUES(23, 9, NULL, 8, '8vo de basica', NULL, true, 100, NULL)
GO
INSERT INTO "public"."curso"("id_curso", "id_seccion", "id_curso_ante", "id_curso_base", "nombre", "descripcion", "activo", "cupo", "estudiantes_por_paralelo")
  VALUES(24, 9, NULL, 9, '10mo de basica', NULL, true, 100, NULL)
GO
INSERT INTO "public"."curso"("id_curso", "id_seccion", "id_curso_ante", "id_curso_base", "nombre", "descripcion", "activo", "cupo", "estudiantes_por_paralelo")
  VALUES(22, 9, NULL, 7, '9no de basica', NULL, true, 100, NULL)
GO
INSERT INTO "public"."curso"("id_curso", "id_seccion", "id_curso_ante", "id_curso_base", "nombre", "descripcion", "activo", "cupo", "estudiantes_por_paralelo")
  VALUES(19, 7, NULL, 4, '5to de basica', NULL, true, 100, NULL)
GO
INSERT INTO "public"."curso"("id_curso", "id_seccion", "id_curso_ante", "id_curso_base", "nombre", "descripcion", "activo", "cupo", "estudiantes_por_paralelo")
  VALUES(25, 11, NULL, 10, '1ro diversificado', NULL, true, 100, NULL)
GO
INSERT INTO "public"."curso"("id_curso", "id_seccion", "id_curso_ante", "id_curso_base", "nombre", "descripcion", "activo", "cupo", "estudiantes_por_paralelo")
  VALUES(28, 12, NULL, 13, '1ro diversificado', NULL, true, 100, NULL)
GO
INSERT INTO "public"."curso"("id_curso", "id_seccion", "id_curso_ante", "id_curso_base", "nombre", "descripcion", "activo", "cupo", "estudiantes_por_paralelo")
  VALUES(18, 7, NULL, 3, '3ro de basica', NULL, true, 100, NULL)
GO
INSERT INTO "public"."curso"("id_curso", "id_seccion", "id_curso_ante", "id_curso_base", "nombre", "descripcion", "activo", "cupo", "estudiantes_por_paralelo")
  VALUES(29, 12, NULL, 14, '2do diversificado', NULL, true, 100, NULL)
GO
INSERT INTO "public"."curso"("id_curso", "id_seccion", "id_curso_ante", "id_curso_base", "nombre", "descripcion", "activo", "cupo", "estudiantes_por_paralelo")
  VALUES(26, 11, NULL, 11, '2do diversificado', NULL, true, 100, NULL)
GO
INSERT INTO "public"."curso"("id_curso", "id_seccion", "id_curso_ante", "id_curso_base", "nombre", "descripcion", "activo", "cupo", "estudiantes_por_paralelo")
  VALUES(27, 11, NULL, 12, '3ro diversificado', NULL, true, 100, NULL)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(12, 1)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(9, 1)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(10, 1)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(11, 1)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(13, 1)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(14, 1)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(8, 1)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(7, 1)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(5, 1)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(4, 1)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(3, 1)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(2, 1)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(1, 1)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(1, 2)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(2, 2)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(3, 2)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(4, 2)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(5, 2)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(6, 2)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(7, 2)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(8, 2)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(9, 2)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(10, 2)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(11, 2)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(12, 2)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(13, 2)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(14, 2)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(15, 2)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(12, 3)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(9, 3)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(15, 3)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(10, 3)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(11, 3)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(13, 3)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(14, 3)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(8, 3)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(7, 3)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(6, 3)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(5, 3)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(4, 3)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(3, 3)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(2, 3)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(1, 3)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(1, 4)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(2, 4)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(3, 4)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(4, 4)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(5, 4)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(6, 4)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(7, 4)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(8, 4)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(9, 4)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(10, 4)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(11, 4)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(12, 4)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(13, 4)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(14, 4)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(15, 4)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(30, 8)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(30, 9)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(21, 6)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(21, 7)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(21, 8)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(23, 5)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(23, 6)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(23, 7)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(23, 8)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(23, 11)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(16, 5)
GO
INSERT INTO "public"."curso_materia"("id_curso", "id_materia")
  VALUES(16, 11)
GO
INSERT INTO "public"."detalle_catalogo"("id_det_cat", "id_cat_tip", "nemonico", "nombre", "descripcion", "activo")
  VALUES(1, 1, 'uio', 'quito', 'quito', true)
GO
INSERT INTO "public"."materia"("id_materia", "id_ue", "id_materia_base", "id_tip_materia", "nombre", "descripcion", "contenidos", "activo")
  VALUES(4, NULL, NULL, NULL, 'Ingles', 'Ingles', 'Mucho Ingles', true)
GO
INSERT INTO "public"."materia"("id_materia", "id_ue", "id_materia_base", "id_tip_materia", "nombre", "descripcion", "contenidos", "activo")
  VALUES(1, NULL, NULL, NULL, 'Matematicas', 'Matematicas', 'Muchas Matematicas', true)
GO
INSERT INTO "public"."materia"("id_materia", "id_ue", "id_materia_base", "id_tip_materia", "nombre", "descripcion", "contenidos", "activo")
  VALUES(2, NULL, NULL, NULL, 'EESS', 'EESS', 'Muchos EESS', true)
GO
INSERT INTO "public"."materia"("id_materia", "id_ue", "id_materia_base", "id_tip_materia", "nombre", "descripcion", "contenidos", "activo")
  VALUES(3, NULL, NULL, NULL, 'CCNN', 'CCNN', 'Muchas CCNN', true)
GO
INSERT INTO "public"."materia"("id_materia", "id_ue", "id_materia_base", "id_tip_materia", "nombre", "descripcion", "contenidos", "activo")
  VALUES(5, 1, 1, NULL, 'Matematicas', 'Matematicas', 'Muchas Matematicas', true)
GO
INSERT INTO "public"."materia"("id_materia", "id_ue", "id_materia_base", "id_tip_materia", "nombre", "descripcion", "contenidos", "activo")
  VALUES(6, 1, 2, NULL, 'EESS', 'EESS', 'Muchos EESS', true)
GO
INSERT INTO "public"."materia"("id_materia", "id_ue", "id_materia_base", "id_tip_materia", "nombre", "descripcion", "contenidos", "activo")
  VALUES(7, 1, 3, NULL, 'CCNN', 'CCNN', 'Muchas CCNN', true)
GO
INSERT INTO "public"."materia"("id_materia", "id_ue", "id_materia_base", "id_tip_materia", "nombre", "descripcion", "contenidos", "activo")
  VALUES(8, 1, 4, NULL, 'Ingles', 'Ingles', 'Mucho Ingles', true)
GO
INSERT INTO "public"."materia"("id_materia", "id_ue", "id_materia_base", "id_tip_materia", "nombre", "descripcion", "contenidos", "activo")
  VALUES(9, 1, NULL, NULL, 'Frances', 'Frances', 'Mucho Frances', true)
GO
INSERT INTO "public"."materia"("id_materia", "id_ue", "id_materia_base", "id_tip_materia", "nombre", "descripcion", "contenidos", "activo")
  VALUES(10, 1, NULL, NULL, 'Aleman', 'Aleman', 'Mucho Aleman', true)
GO
INSERT INTO "public"."materia"("id_materia", "id_ue", "id_materia_base", "id_tip_materia", "nombre", "descripcion", "contenidos", "activo")
  VALUES(11, 1, 1, NULL, 'Mate Avanzada', 'Mate Avanzada', 'Mate Avanzada', true)
GO
INSERT INTO "public"."opcion"("nombre", "id_opcion", "descripcion", "url", "id_opcion_padre", "tipo", "tipo_desc")
  VALUES('perfiles', 4, 'perfiles', '#', NULL, 0, NULL)
GO
INSERT INTO "public"."opcion"("nombre", "id_opcion", "descripcion", "url", "id_opcion_padre", "tipo", "tipo_desc")
  VALUES('perfil', 5, 'perfil', 'perfil', 4, 0, NULL)
GO
INSERT INTO "public"."opcion"("nombre", "id_opcion", "descripcion", "url", "id_opcion_padre", "tipo", "tipo_desc")
  VALUES('información institucional', 1, 'información institucional', 'informacion-institucional', 2, 0, 'todos pueden ver esta opcion')
GO
INSERT INTO "public"."opcion"("nombre", "id_opcion", "descripcion", "url", "id_opcion_padre", "tipo", "tipo_desc")
  VALUES('información institucional', 6, 'información institucional', 'informacion-institucional', 2, 10, NULL)
GO
INSERT INTO "public"."opcion"("nombre", "id_opcion", "descripcion", "url", "id_opcion_padre", "tipo", "tipo_desc")
  VALUES('perfil', 7, 'perfil', 'perfil', 4, 10, NULL)
GO
INSERT INTO "public"."opcion"("nombre", "id_opcion", "descripcion", "url", "id_opcion_padre", "tipo", "tipo_desc")
  VALUES('perfiles', 8, 'buscar perfiles', 'perfiles', 4, 10, '')
GO
INSERT INTO "public"."opcion"("nombre", "id_opcion", "descripcion", "url", "id_opcion_padre", "tipo", "tipo_desc")
  VALUES('academico', 9, 'academico', 'academico', NULL, 10, NULL)
GO
INSERT INTO "public"."opcion"("nombre", "id_opcion", "descripcion", "url", "id_opcion_padre", "tipo", "tipo_desc")
  VALUES('pensum', 10, 'pensum', 'pensum', 9, 10, NULL)
GO
INSERT INTO "public"."opcion"("nombre", "id_opcion", "descripcion", "url", "id_opcion_padre", "tipo", "tipo_desc")
  VALUES('configuracion', 2, 'configuracion', '#', NULL, 0, 'todos pueden ver esta opcion')
GO
INSERT INTO "public"."pais"("id_pai", "nombre", "descripcion", "observacion", "nemonico", "activo")
  VALUES(1, 'ecuador', 'ecuador', 'ecuador', 'ec', true)
GO
INSERT INTO "public"."persona"("id_persona", "id_det_cat", "nombres", "apellidos", "ci_pasaporte", "fecha_nacimiento", "usuario", "contrasena", "activo", "perfil", "telefono_contacto_1", "telefono_contacto_2", "e_mail_personal")
  VALUES(2, 1, 'pedro', 'perez', '1234567891', '2012-10-12', 'pedro', '123', true, 'perfil', '123456', '4564321', 'zxc@asd.com')
GO
INSERT INTO "public"."persona"("id_persona", "id_det_cat", "nombres", "apellidos", "ci_pasaporte", "fecha_nacimiento", "usuario", "contrasena", "activo", "perfil", "telefono_contacto_1", "telefono_contacto_2", "e_mail_personal")
  VALUES(1, 1, 'xavier', 'ramirez', '1718263153', '2012-10-12', 'xaviercobain88', 'aIeH2P8UTFAsf1z/qv4sxYjYYHn53ogwTCawy5nOkcY=', true, 'perfil', '2632264', '084949453', 'xaviercobain88@hotmail.com')
GO
INSERT INTO "public"."region"("id_reg", "id_pai", "nombre", "descripcion", "observacion", "nemonico", "activo")
  VALUES(1, 1, 'sierra', 'sierra', 'sierra', 'sie', true)
GO
INSERT INTO "public"."rol"("id_rol", "rol", "id_ue")
  VALUES(1, 'administrador', 1)
GO
INSERT INTO "public"."rol_opcion"("id_opcion", "id_rol")
  VALUES(2, 1)
GO
INSERT INTO "public"."rol_opcion"("id_opcion", "id_rol")
  VALUES(4, 1)
GO
INSERT INTO "public"."rol_opcion"("id_opcion", "id_rol")
  VALUES(5, 1)
GO
INSERT INTO "public"."rol_opcion"("id_opcion", "id_rol")
  VALUES(7, 1)
GO
INSERT INTO "public"."rol_opcion"("id_opcion", "id_rol")
  VALUES(6, 1)
GO
INSERT INTO "public"."rol_opcion"("id_opcion", "id_rol")
  VALUES(8, 1)
GO
INSERT INTO "public"."rol_opcion"("id_opcion", "id_rol")
  VALUES(9, 1)
GO
INSERT INTO "public"."rol_opcion"("id_opcion", "id_rol")
  VALUES(10, 1)
GO
INSERT INTO "public"."rol_persona"("id_rol", "id_persona")
  VALUES(1, 1)
GO
INSERT INTO "public"."rol_persona"("id_rol", "id_persona")
  VALUES(1, 2)
GO
INSERT INTO "public"."seccion"("id_seccion", "id_ue", "id_seccion_padre", "id_seccion_base", "nombre", "descripcion", "activo", "minimo_aprobacion", "nombre_division", "cantidad_division", "nombre_subdivision", "cantidad_subdivision", "estudiantes_por_curso", "implementacion")
  VALUES(2, NULL, NULL, NULL, 'Secundaria', 'Secundaria', true, 14, NULL, NULL, NULL, NULL, NULL, false)
GO
INSERT INTO "public"."seccion"("id_seccion", "id_ue", "id_seccion_padre", "id_seccion_base", "nombre", "descripcion", "activo", "minimo_aprobacion", "nombre_division", "cantidad_division", "nombre_subdivision", "cantidad_subdivision", "estudiantes_por_curso", "implementacion")
  VALUES(4, NULL, 2, NULL, 'Ciclo Diversificado', 'Ciclo Diversificado', true, 14, NULL, NULL, NULL, NULL, NULL, false)
GO
INSERT INTO "public"."seccion"("id_seccion", "id_ue", "id_seccion_padre", "id_seccion_base", "nombre", "descripcion", "activo", "minimo_aprobacion", "nombre_division", "cantidad_division", "nombre_subdivision", "cantidad_subdivision", "estudiantes_por_curso", "implementacion")
  VALUES(8, 1, NULL, 2, 'Secundaria', 'Secundaria', true, 14, NULL, NULL, NULL, NULL, NULL, false)
GO
INSERT INTO "public"."seccion"("id_seccion", "id_ue", "id_seccion_padre", "id_seccion_base", "nombre", "descripcion", "activo", "minimo_aprobacion", "nombre_division", "cantidad_division", "nombre_subdivision", "cantidad_subdivision", "estudiantes_por_curso", "implementacion")
  VALUES(3, NULL, 2, NULL, 'Ciclo Basico', 'Ciclo Basico', true, 14, 'Curso', 3, 'Paralelo', NULL, NULL, true)
GO
INSERT INTO "public"."seccion"("id_seccion", "id_ue", "id_seccion_padre", "id_seccion_base", "nombre", "descripcion", "activo", "minimo_aprobacion", "nombre_division", "cantidad_division", "nombre_subdivision", "cantidad_subdivision", "estudiantes_por_curso", "implementacion")
  VALUES(5, NULL, 4, NULL, 'FIMA', 'FIMA', true, 14, 'Curso', 3, 'Paralelo', NULL, NULL, true)
GO
INSERT INTO "public"."seccion"("id_seccion", "id_ue", "id_seccion_padre", "id_seccion_base", "nombre", "descripcion", "activo", "minimo_aprobacion", "nombre_division", "cantidad_division", "nombre_subdivision", "cantidad_subdivision", "estudiantes_por_curso", "implementacion")
  VALUES(6, NULL, 4, NULL, 'QUIBIO', 'QUIBIO', true, 14, 'Curso', 3, 'Paralelo', NULL, NULL, true)
GO
INSERT INTO "public"."seccion"("id_seccion", "id_ue", "id_seccion_padre", "id_seccion_base", "nombre", "descripcion", "activo", "minimo_aprobacion", "nombre_division", "cantidad_division", "nombre_subdivision", "cantidad_subdivision", "estudiantes_por_curso", "implementacion")
  VALUES(1, NULL, NULL, NULL, 'Primaria', 'Primaria', true, 14, 'Curso', 6, 'Paralelo', NULL, NULL, true)
GO
INSERT INTO "public"."seccion"("id_seccion", "id_ue", "id_seccion_padre", "id_seccion_base", "nombre", "descripcion", "activo", "minimo_aprobacion", "nombre_division", "cantidad_division", "nombre_subdivision", "cantidad_subdivision", "estudiantes_por_curso", "implementacion")
  VALUES(7, 1, NULL, 1, 'Primaria', 'Primaria', true, 14, 'Curso', 6, 'Paralelo', 3, 20, true)
GO
INSERT INTO "public"."seccion"("id_seccion", "id_ue", "id_seccion_padre", "id_seccion_base", "nombre", "descripcion", "activo", "minimo_aprobacion", "nombre_division", "cantidad_division", "nombre_subdivision", "cantidad_subdivision", "estudiantes_por_curso", "implementacion")
  VALUES(12, 1, 10, 6, 'QUIBIO', 'QUIBIO', true, 14, 'Curso', 3, 'Paralelo', 3, 20, true)
GO
INSERT INTO "public"."seccion"("id_seccion", "id_ue", "id_seccion_padre", "id_seccion_base", "nombre", "descripcion", "activo", "minimo_aprobacion", "nombre_division", "cantidad_division", "nombre_subdivision", "cantidad_subdivision", "estudiantes_por_curso", "implementacion")
  VALUES(9, 1, 8, 3, 'Ciclo Basico', 'Ciclo Basico', true, 14, 'Curso', 3, 'Paralelo', 3, 20, true)
GO
INSERT INTO "public"."seccion"("id_seccion", "id_ue", "id_seccion_padre", "id_seccion_base", "nombre", "descripcion", "activo", "minimo_aprobacion", "nombre_division", "cantidad_division", "nombre_subdivision", "cantidad_subdivision", "estudiantes_por_curso", "implementacion")
  VALUES(10, 1, 8, 4, 'Ciclo Diversificado', 'Ciclo Diversificado', true, 14, NULL, NULL, NULL, NULL, NULL, false)
GO
INSERT INTO "public"."seccion"("id_seccion", "id_ue", "id_seccion_padre", "id_seccion_base", "nombre", "descripcion", "activo", "minimo_aprobacion", "nombre_division", "cantidad_division", "nombre_subdivision", "cantidad_subdivision", "estudiantes_por_curso", "implementacion")
  VALUES(11, 1, 10, 5, 'FIMA', 'FIMA', true, 14, 'Curso', 3, 'Paralelo', 3, 20, true)
GO
INSERT INTO "public"."unidad_educativa"("id_ue", "id_reg", "nombre", "slogan", "mision", "vision", "direccion", "telefono_1", "telefono_3", "telefono_2", "nombre_contacto_adm", "telefono_contacto_adm", "e_mail_contacto_adm", "descripcion", "activo", "e_mail", "website", "director", "foto_escudo_dir", "foto_director_dir", "provincia", "canton", "parroquia", "tipo_institucion")
  VALUES(1, 1, 'Pobre latuga', '', '', '', '', '2222222', NULL, '', 'gilberto freyre', '2222222', NULL, NULL, true, '', '', '', NULL, NULL, 'pichincha', 'quito', 'la magdalena', 'colegio')
GO
ALTER TABLE "public"."catalogo_tipo"
	ADD CONSTRAINT "fk_catalogo_r_cat_tip_catalogo"
	FOREIGN KEY("cat_id_cat_tip")
	REFERENCES "public"."catalogo_tipo"("id_cat_tip")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."clase"
	ADD CONSTRAINT "fk_clase_r_pers_cl_persona"
	FOREIGN KEY("id_persona")
	REFERENCES "public"."persona"("id_persona")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."clase"
	ADD CONSTRAINT "fk_clase_r_per_cla_periodo"
	FOREIGN KEY("id_per")
	REFERENCES "public"."periodo"("id_per")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."clase"
	ADD CONSTRAINT "fk_clase_r_par_cla_paralelo"
	FOREIGN KEY("id_paralelo")
	REFERENCES "public"."paralelo"("id_paralelo")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."clase"
	ADD CONSTRAINT "fk_clase_r_mat_cla_materia"
	FOREIGN KEY("id_materia")
	REFERENCES "public"."materia"("id_materia")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."configuracion_sistema"
	ADD CONSTRAINT "fk_configur_r_pers_co_persona"
	FOREIGN KEY("id_persona")
	REFERENCES "public"."persona"("id_persona")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."contenido"
	ADD CONSTRAINT "fk_contenid_r_mes_set_mes_setu"
	FOREIGN KEY("id_mes_setup")
	REFERENCES "public"."mes_setup"("id_mes_setup")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."contenido"
	ADD CONSTRAINT "fk_contenid_r_mat_con_materia"
	FOREIGN KEY("id_materia")
	REFERENCES "public"."materia"("id_materia")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."continuidad_materia"
	ADD CONSTRAINT "fk_continui_r_sec_sig"
	FOREIGN KEY("id_materia_sig")
	REFERENCES "public"."materia"("id_materia")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."continuidad_materia"
	ADD CONSTRAINT "fk_continui_r_sec_ante"
	FOREIGN KEY("id_materia_ante")
	REFERENCES "public"."materia"("id_materia")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."continuidad_seccion"
	ADD CONSTRAINT "fk_continui_r_sec_sig_seccion"
	FOREIGN KEY("sec_id_seccion")
	REFERENCES "public"."seccion"("id_seccion")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."continuidad_seccion"
	ADD CONSTRAINT "fk_continui_r_sec_ant_seccion"
	FOREIGN KEY("id_seccion")
	REFERENCES "public"."seccion"("id_seccion")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."curso"
	ADD CONSTRAINT "fk_curso_r_sec_cur_seccion"
	FOREIGN KEY("id_seccion")
	REFERENCES "public"."seccion"("id_seccion")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."curso"
	ADD CONSTRAINT "fk_curso_r_cur_base"
	FOREIGN KEY("id_curso_base")
	REFERENCES "public"."curso"("id_curso")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."curso"
	ADD CONSTRAINT "fk_curso_r_cur_ante"
	FOREIGN KEY("id_curso_ante")
	REFERENCES "public"."curso"("id_curso")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."curso_materia"
	ADD CONSTRAINT "fk_curso_ma_r_mat_tr__materia"
	FOREIGN KEY("id_materia")
	REFERENCES "public"."materia"("id_materia")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."curso_materia"
	ADD CONSTRAINT "fk_curso_ma_r_cur_tr__curso"
	FOREIGN KEY("id_curso")
	REFERENCES "public"."curso"("id_curso")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."datos_empleado_ue"
	ADD CONSTRAINT "fk_datos_em_r_uni_edu_unidad_e"
	FOREIGN KEY("id_ue")
	REFERENCES "public"."unidad_educativa"("id_ue")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."datos_empleado_ue"
	ADD CONSTRAINT "fk_datos_em_r_per_dat_persona"
	FOREIGN KEY("id_persona")
	REFERENCES "public"."persona"("id_persona")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."datos_estudiante"
	ADD CONSTRAINT "fk_datos_es_r_pers_da_persona"
	FOREIGN KEY("id_persona")
	REFERENCES "public"."persona"("id_persona")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."datos_representante"
	ADD CONSTRAINT "fk_datos_re_r_pers_da_persona"
	FOREIGN KEY("id_persona")
	REFERENCES "public"."persona"("id_persona")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."detalle_catalogo"
	ADD CONSTRAINT "fk_detalle__r_cat_tip_catalogo"
	FOREIGN KEY("id_cat_tip")
	REFERENCES "public"."catalogo_tipo"("id_cat_tip")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."dia_festivo"
	ADD CONSTRAINT "fk_dia_fest_r_per_dia_periodo"
	FOREIGN KEY("id_per")
	REFERENCES "public"."periodo"("id_per")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."estudiante_representante"
	ADD CONSTRAINT "fk_estudian_r_per_tr__persona"
	FOREIGN KEY("id_persona")
	REFERENCES "public"."persona"("id_persona")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."estudiante_representante"
	ADD CONSTRAINT "fk_estudian_r_per_tr__per"
	FOREIGN KEY("per_id_persona")
	REFERENCES "public"."persona"("id_persona")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."estudiante_representante"
	ADD CONSTRAINT "fk_estudian_r_det_cat_detalle_"
	FOREIGN KEY("id_det_cat")
	REFERENCES "public"."detalle_catalogo"("id_det_cat")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."grupo"
	ADD CONSTRAINT "fk_grupo_r_pers_gr_persona"
	FOREIGN KEY("id_persona")
	REFERENCES "public"."persona"("id_persona")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."grupo"
	ADD CONSTRAINT "fk_grupo_r_her_cla_herramie"
	FOREIGN KEY("id_her_cla")
	REFERENCES "public"."herramienta_clase"("id_her_cla")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."herramienta_clase"
	ADD CONSTRAINT "fk_herramie_r_tr_mes__mes_clas"
	FOREIGN KEY("id_mes_setup", "id_clase")
	REFERENCES "public"."mes_clase"("id_mes_setup", "id_clase")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."herramienta_clase"
	ADD CONSTRAINT "fk_herramie_r_her_eva_herramie"
	FOREIGN KEY("id_her_eva")
	REFERENCES "public"."herramienta_evaluacion"("id_her_eva")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."herramienta_clase"
	ADD CONSTRAINT "fk_herramie_r_her_cla_herramie"
	FOREIGN KEY("id_her_cla_agr")
	REFERENCES "public"."herramienta_clase_agrupacion"("id_her_cla_agr")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."herramienta_clase_agrupacion"
	ADD CONSTRAINT "fk_herramie_r_sec_her_seccion"
	FOREIGN KEY("id_seccion")
	REFERENCES "public"."seccion"("id_seccion")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."historico_academico_anual"
	ADD CONSTRAINT "fk_historic_r_profe_h_persona"
	FOREIGN KEY("per_id_persona")
	REFERENCES "public"."persona"("id_persona")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."historico_academico_anual"
	ADD CONSTRAINT "fk_historic_r_pers_hi_persona"
	FOREIGN KEY("id_persona")
	REFERENCES "public"."persona"("id_persona")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."historico_academico_anual"
	ADD CONSTRAINT "fk_historic_r_per_his_periodo"
	FOREIGN KEY("id_per")
	REFERENCES "public"."periodo"("id_per")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."historico_academico_anual"
	ADD CONSTRAINT "fk_historic_r_mat_his_materia"
	FOREIGN KEY("id_materia")
	REFERENCES "public"."materia"("id_materia")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."historico_academico_mensual"
	ADD CONSTRAINT "fk_historic_r_profe_h_persona"
	FOREIGN KEY("per_id_persona")
	REFERENCES "public"."persona"("id_persona")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."historico_academico_mensual"
	ADD CONSTRAINT "fk_historic_r_pers_hi_persona"
	FOREIGN KEY("id_persona")
	REFERENCES "public"."persona"("id_persona")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."historico_academico_mensual"
	ADD CONSTRAINT "fk_historic_r_per_his_periodo"
	FOREIGN KEY("id_per")
	REFERENCES "public"."periodo"("id_per")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."historico_academico_mensual"
	ADD CONSTRAINT "fk_historic_r_mes_set_mes_setu"
	FOREIGN KEY("id_mes_setup")
	REFERENCES "public"."mes_setup"("id_mes_setup")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."historico_academico_mensual"
	ADD CONSTRAINT "fk_historic_r_mat_his_materia"
	FOREIGN KEY("id_materia")
	REFERENCES "public"."materia"("id_materia")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."historico_materia"
	ADD CONSTRAINT "fk_historic_r_pers_hi_persona"
	FOREIGN KEY("id_persona")
	REFERENCES "public"."persona"("id_persona")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."historico_materia"
	ADD CONSTRAINT "fk_historic_r_per_his_periodo"
	FOREIGN KEY("id_per")
	REFERENCES "public"."periodo"("id_per")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."historico_materia"
	ADD CONSTRAINT "fk_historic_r_mat_his_materia"
	FOREIGN KEY("id_materia")
	REFERENCES "public"."materia"("id_materia")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."historico_materia"
	ADD CONSTRAINT "fk_historic_r_cur_his_curso"
	FOREIGN KEY("id_curso")
	REFERENCES "public"."curso"("id_curso")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."materia"
	ADD CONSTRAINT "fk_materia_r_uni_edu_unidad_e"
	FOREIGN KEY("id_ue")
	REFERENCES "public"."unidad_educativa"("id_ue")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."materia"
	ADD CONSTRAINT "fk_materia_r_tip_mat_tipo_mat"
	FOREIGN KEY("id_tip_materia")
	REFERENCES "public"."tipo_materia"("id_tip_materia")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."materia"
	ADD CONSTRAINT "fk_materia_r_mat_base"
	FOREIGN KEY("id_materia_base")
	REFERENCES "public"."materia"("id_materia")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."matricula"
	ADD CONSTRAINT "fk_matricul_r_pers_ma_persona"
	FOREIGN KEY("id_persona")
	REFERENCES "public"."persona"("id_persona")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."matricula"
	ADD CONSTRAINT "fk_matricul_r_per_mat_periodo"
	FOREIGN KEY("id_per")
	REFERENCES "public"."periodo"("id_per")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."matricula"
	ADD CONSTRAINT "fk_matricul_r_par_mat_paralelo"
	FOREIGN KEY("id_paralelo")
	REFERENCES "public"."paralelo"("id_paralelo")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."mes_clase"
	ADD CONSTRAINT "fk_mes_clas_r_mes_set_mes_setu"
	FOREIGN KEY("id_mes_setup")
	REFERENCES "public"."mes_setup"("id_mes_setup")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."mes_clase"
	ADD CONSTRAINT "fk_mes_clas_r_cla_tr__clase"
	FOREIGN KEY("id_clase")
	REFERENCES "public"."clase"("id_clase")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."mes_setup"
	ADD CONSTRAINT "fk_mes_setu_r_sec_mes_seccion"
	FOREIGN KEY("id_seccion")
	REFERENCES "public"."seccion"("id_seccion")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."nota"
	ADD CONSTRAINT "fk_nota_r_mat_not_matricul"
	FOREIGN KEY("id_matricula")
	REFERENCES "public"."matricula"("id_matricula")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."nota"
	ADD CONSTRAINT "fk_nota_r_her_cla_herramie"
	FOREIGN KEY("id_her_cla")
	REFERENCES "public"."herramienta_clase"("id_her_cla")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."opcion"
	ADD CONSTRAINT "fk_opcion_relations_opcion"
	FOREIGN KEY("id_opcion_padre")
	REFERENCES "public"."opcion"("id_opcion")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."opcion_pregunta"
	ADD CONSTRAINT "fk_opcion_p_r_pre_opc_pregunta"
	FOREIGN KEY("id_pregunta")
	REFERENCES "public"."pregunta"("id_pregunta")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."opcion_respuesta"
	ADD CONSTRAINT "fk_opcion_r_r_res_opc_respuest"
	FOREIGN KEY("id_respuesta")
	REFERENCES "public"."respuesta"("id_respuesta")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."opcion_respuesta"
	ADD CONSTRAINT "fk_opcion_r_r_opc_pre_opcion_p"
	FOREIGN KEY("id_opcion_pregunta")
	REFERENCES "public"."opcion_pregunta"("id_opcion_pregunta")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."paralelo"
	ADD CONSTRAINT "fk_paralelo_r_cur_par_curso"
	FOREIGN KEY("id_curso")
	REFERENCES "public"."curso"("id_curso")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."periodo"
	ADD CONSTRAINT "fk_periodo_r_reg_per_region"
	FOREIGN KEY("id_reg")
	REFERENCES "public"."region"("id_reg")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."persona"
	ADD CONSTRAINT "fk_persona_r_det_cat_detalle_"
	FOREIGN KEY("id_det_cat")
	REFERENCES "public"."detalle_catalogo"("id_det_cat")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."persona_grupo"
	ADD CONSTRAINT "fk_persona__r_per_tr__persona"
	FOREIGN KEY("id_persona")
	REFERENCES "public"."persona"("id_persona")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."persona_grupo"
	ADD CONSTRAINT "fk_persona__r_gru_tr__grupo"
	FOREIGN KEY("id_grupo")
	REFERENCES "public"."grupo"("id_grupo")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."pregunta"
	ADD CONSTRAINT "fk_pregunta_r_her_eva_herramie"
	FOREIGN KEY("id_her_eva")
	REFERENCES "public"."herramienta_evaluacion"("id_her_eva")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."recurso"
	ADD CONSTRAINT "fk_recurso_r_her_eva_herramie"
	FOREIGN KEY("id_her_eva")
	REFERENCES "public"."herramienta_evaluacion"("id_her_eva")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."recurso"
	ADD CONSTRAINT "fk_recurso_r_det_cat_detalle_"
	FOREIGN KEY("id_det_cat")
	REFERENCES "public"."detalle_catalogo"("id_det_cat")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."recurso_herramienta_clase"
	ADD CONSTRAINT "fk_recurso__r_rec_tr__recurso"
	FOREIGN KEY("id_recurso")
	REFERENCES "public"."recurso"("id_recurso")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."recurso_herramienta_clase"
	ADD CONSTRAINT "fk_recurso__r_her_cla_herramie"
	FOREIGN KEY("id_her_cla")
	REFERENCES "public"."herramienta_clase"("id_her_cla")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."recurso_herramienta_evaluacion"
	ADD CONSTRAINT "fk_recurso__r_rec_tr__recurso"
	FOREIGN KEY("id_recurso")
	REFERENCES "public"."recurso"("id_recurso")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."recurso_herramienta_evaluacion"
	ADD CONSTRAINT "fk_recurso__r_her_eva_herramie"
	FOREIGN KEY("id_her_eva")
	REFERENCES "public"."herramienta_evaluacion"("id_her_eva")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."recurso_keyword"
	ADD CONSTRAINT "fk_recurso__r_rec_tr__recurso"
	FOREIGN KEY("id_recurso")
	REFERENCES "public"."recurso"("id_recurso")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."recurso_keyword"
	ADD CONSTRAINT "fk_recurso__r_key_tr__detalle_"
	FOREIGN KEY("id_det_cat")
	REFERENCES "public"."detalle_catalogo"("id_det_cat")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."recurso_materia"
	ADD CONSTRAINT "fk_recurso__r_rec_tr__recurso"
	FOREIGN KEY("id_recurso")
	REFERENCES "public"."recurso"("id_recurso")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."recurso_materia"
	ADD CONSTRAINT "fk_recurso__r_mat_tr__materia"
	FOREIGN KEY("id_materia")
	REFERENCES "public"."materia"("id_materia")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."region"
	ADD CONSTRAINT "fk_region_r_pai_reg_pais"
	FOREIGN KEY("id_pai")
	REFERENCES "public"."pais"("id_pai")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."registro"
	ADD CONSTRAINT "fk_registro_r_tr_mes__mes_clas"
	FOREIGN KEY("id_mes_setup", "id_clase")
	REFERENCES "public"."mes_clase"("id_mes_setup", "id_clase")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."respuesta"
	ADD CONSTRAINT "fk_respuest_r_pre_res_pregunta"
	FOREIGN KEY("id_pregunta")
	REFERENCES "public"."pregunta"("id_pregunta")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."respuesta"
	ADD CONSTRAINT "fk_respuest_r_not_res_nota"
	FOREIGN KEY("id_nota")
	REFERENCES "public"."nota"("id_nota")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."rol"
	ADD CONSTRAINT "fk_rol_r_uni_edu"
	FOREIGN KEY("id_ue")
	REFERENCES "public"."unidad_educativa"("id_ue")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."rol_opcion"
	ADD CONSTRAINT "fk_rol_opci_relations_rol"
	FOREIGN KEY("id_rol")
	REFERENCES "public"."rol"("id_rol")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."rol_opcion"
	ADD CONSTRAINT "fk_rol_opci_relations_opcion"
	FOREIGN KEY("id_opcion")
	REFERENCES "public"."opcion"("id_opcion")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."rol_persona"
	ADD CONSTRAINT "fk_rol_pers_r_rol_tr__rol"
	FOREIGN KEY("id_rol")
	REFERENCES "public"."rol"("id_rol")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."rol_persona"
	ADD CONSTRAINT "fk_rol_pers_r_pers_tr_persona"
	FOREIGN KEY("id_persona")
	REFERENCES "public"."persona"("id_persona")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."seccion"
	ADD CONSTRAINT "fk_seccion_relations_padre"
	FOREIGN KEY("id_seccion_base")
	REFERENCES "public"."seccion"("id_seccion")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."seccion"
	ADD CONSTRAINT "fk_seccion_relations_base"
	FOREIGN KEY("id_seccion_base")
	REFERENCES "public"."seccion"("id_seccion")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."seccion"
	ADD CONSTRAINT "fk_seccion_r_uni_edu_unidad_e"
	FOREIGN KEY("id_ue")
	REFERENCES "public"."unidad_educativa"("id_ue")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
ALTER TABLE "public"."unidad_educativa"
	ADD CONSTRAINT "fk_unidad_e_r_reg_uni_region"
	FOREIGN KEY("id_reg")
	REFERENCES "public"."region"("id_reg")
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT 
GO
